### ISSUE TITLE
Notification Email sent with incorrect Developer Portal Link

### ISSUE THREAD

**Issue by Harjindar** [Azure/api-management-developer-portal#473] opened 2020-02-11 22:41 UTC
- We configured Custom Domain and it works correctly. 
- On the overview page the developer portal link is shown as expected
![image](https://user-images.githubusercontent.com/37382131/74286222-9b224880-4d27-11ea-9a7a-5297844e5def.png)
- Then we use invite user functionality and select Developer portal
- This email is sent correctly with correct custom domain URL
- Then we add a subscription for this user from the Azure Portal
- The _Your subscription to the Starter_ email is sent with incorrect link. This is the link to the standard azure **legacy** portal  link instead of custom domain Developer portal. 
![image](https://user-images.githubusercontent.com/37382131/74286415-ff450c80-4d27-11ea-9db8-3bd5b4166a2a.png)
- This applies to all the emails using the $DevPortalUrl parameter in the Notification templates. 
Problems seems with  $DevPortalUrl parameter which is somehow referring to legacy Developer Portal url

This is quite ugly and makes the whole custom domain useless..

**Comment by ygrik** [comment] 2020-02-11 22:53
@Harjindar this is a known issue.
We will fix it as soon as have time. 
As a workaround, you can hard code your custom URL in the email template.
Anyway, you need to change this template and remove the link to the Issues page that does not exist on the new developer portal.

**Comment by Harjindar** [comment] 2020-02-12 08:39
Thanks, hard-code url is indeed the workaround which we had in mind.

**Comment by mikebudzynski** [comment] 2020-06-15 22:36
We're actively working on a solution. cc: @ygrik

**Comment by mikebudzynski** [comment] 2020-07-13 21:27
The fix is included in the release we're rolling out now. ETA for full deployment is ~2 weeks.

**Closed** 2020-07-14 20:40 UTC
Labels: P0, bug, in-progress

**Comment by memblin-taurus** [comment] 2020-12-15 00:01
This still seems to be a bug or otherwise if it was fixed a regression.

**Comment by manjzu** [comment] 2024-01-09 11:48
This issue seems to be still present, can we please reopen this issue? @mikebudzynski 

It's not working "Developer welcome letter" template for us, otherwise for other templates its working fine.

**Comment by maqsLV** [comment] 2025-03-27 09:53
**This issue is still present, only for the `QuotaLimitApproachingDeveloperNotificationMessage`.**
While for other templates we use all is perfectly fine and Custom Domain substitution for $DevPortalUrl.
As a workaround I'm doing replacement in scope of Bicep deployment of these templates APIM:
```bicep
resource apimNotifications_QuotaLimitApproachingDeveloperNotificationMessage 'Microsoft.ApiManagement/service/templates@2024-05-01' = {
  parent: apim
  name: 'QuotaLimitApproachingDeveloperNotificationMessage'
  properties: {
    subject: 'You are approaching an API quota limit on $ProdName'
    body: replace(loadTextContent('./emailTemplates/QuotaLimitApproachingDeveloperNotificationMessage.html'), '$DevPortalUrl', apimDeveloperPortalCustomDomainNames[0])
  }
}

```
