### ISSUE TITLE
Developer Portal - APIs page Search option only works when 'Group by tag' is on

### ISSUE THREAD

**Issue by DavidFreetly** [Azure/api-management-developer-portal#472] opened 2020-02-11 21:22 UTC
Bug description

In the APIs page of the Developer Portal the 'Search' field only works when the 'Group by tag' option is turned on.

## Reproduction steps

1. Go to Developer Portal
2. Click on APIs menu
3. Click in the Search field
4. Search for an API
5.  The search will not find any APIs matching your search term unless the 'Group by tag' option is turned on.

## Expected behavior

The search field should limit the APIs listed on the page based on the search criteria entered.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser:  Google Chrome

![Screen Shot 2020-02-11 at 3 20 58 PM](https://user-images.githubusercontent.com/4295769/74280448-2e388f80-4ce2-11ea-8bdd-af40ded1b0c3.png)

![Screen Shot 2020-02-11 at 3 21 19 PM](https://user-images.githubusercontent.com/4295769/74280461-34c70700-4ce2-11ea-8a48-ac962bc903df.png)

**Comment by azaslonov** [comment] 2020-02-12 02:17
Hi David, looks like I can't reproduce this. Are there anything specifics to take into account?
![image](https://user-images.githubusercontent.com/2320302/74297110-b4f96680-4cfa-11ea-8146-8eee685c37ba.png)

**Comment by DavidFreetly** [comment] 2020-02-12 12:26
When I search using 'echo' it will work but when I search with other terms it will not find the APIs.  The really odd thing is when I searched with the word 'services' it matched on an API that doesn't contain that word in the name or description.  I've tried on Chrome, Firefox and Safari and all are giving the same result.
![Screen Shot 2020-02-12 at 6 17 17 AM](https://user-images.githubusercontent.com/4295769/74334912-8b732600-4d60-11ea-8d58-95523260eb9f.png)
![Screen Shot 2020-02-12 at 6 17 36 AM](https://user-images.githubusercontent.com/4295769/74334921-9037da00-4d60-11ea-83cb-0aef60b0c44c.png)
![Screen Shot 2020-02-12 at 6 17 52 AM](https://user-images.githubusercontent.com/4295769/74334928-93cb6100-4d60-11ea-9fc1-81712f8d7ce8.png)

**Comment by DavidFreetly** [comment] 2020-02-12 12:35
I think I know what is going on.  It is searching by the Name and not the Display Name of the API.

**Comment by azaslonov** [comment] 2020-02-14 01:53
Indeed!

**Comment by azaslonov** [comment] 2020-02-14 01:55
Fixed in #472.

**Closed** 2020-02-14 17:57 UTC
Labels: bug
