### ISSUE TITLE
String value in response example converted to date even `format: date` is not used

### ISSUE THREAD

**Issue by jarkkojarvinen** [Azure/api-management-developer-portal#2154] opened 2023-04-14 10:52 UTC
## Bug description

String value in response example converted to date even `format: date` is not used

## Reproduction steps

1. Add new API from portal by importing `given-openapi.yaml`
2. Select OpenAPI editor (YAML) and compare code to `given-openapi.yaml`

## Expected behavior

Given OpenAPI specification date and time properties in response example should be same with OpenAPI editor specification. Now time property in example is also date, even it should be string.

## Is your portal managed or self-hosted?

Managed

## Additional context

Add any other context about the problem here, including screenshots.

Given OpenAPI spesification `given-openapi.yaml`:

```yaml
openapi: 3.0.1
info:
  title: demoapi
  description: This is demo API
  version: '1.0'
paths:
  /time:
    get:
      summary: This is demo endpoint
      description: This is demo endpoint
      operationId: get-time
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeResponse'
              example:
                date: '2023-04-14'
                time: '07:49'
components:
  schemas:
    TimeResponse:
      type: object
      properties:
        date:
          type: string
          description: Date
          format: date
          example: '2023-04-14'
        time:
          type: string
          description: Time
          example: '07:49'
      description: Time response
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
```

OpenAPI spesification exported from portal after import of `given-openapi.yaml`:

```yaml
openapi: 3.0.1
info:
  title: demoapi
  description: This is demo API
  version: '1.0'
servers:
  - url: 'https://abc.azure-api.net/demo'
paths:
  /time:
    get:
      summary: This is demo endpoint
      description: This is demo endpoint
      operationId: get-time
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeResponse'
              example:
                date: '2023-04-14'
                time: '2023-04-14'
components:
  schemas:
    TimeResponse:
      type: object
      properties:
        date:
          type: string
          description: Date
          format: date
          example: '2023-04-14'
        time:
          type: string
          description: Time
          example: '07:49'
      description: Time response
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []

```

**Comment by jarkkojarvinen** [comment] 2023-04-14 11:08
There are something odd with date/time formatting. It would be nice if date/time formatting honours standards (https://www.rfc-editor.org/rfc/rfc3339#section-5.6) and OAS 3 practices (https://swagger.io/docs/specification/data-models/data-types/#string)

Or at least fallback to string if format is not supported.

I originally created this kind of bug to APIOps team, but they directed me to APIM team https://github.com/Azure/apiops/issues/266

**Comment by Hekku2** [comment] 2023-05-02 07:33
We're interested in a fix for this issue as well.

**Comment by umashankar337** [comment] 2023-11-05 22:07
Recently we have started using API management and while exporting the API specification in CICD process, we are still getting issue mentioned in https://github.com/Azure/apiops/issues/266 . I also found that in bug https://github.com/Azure/api-management-developer-portal/issues/871 is has been mentioned that the issue is resolved. But it seem not. Can you help me how to solve this issue ?

**Comment by umashankar337** [comment] 2024-01-22 10:58
@mikebudzynski @malincrist Do we have any update on this issue ?

**Comment by jarkkojarvinen** [comment] 2024-02-19 08:58
Almost year gone. Any updates to this? This makes our APIM publish process quite tricky and this makes us to think moving out from APIM usage. At least API's those are changing often.

**Comment by mrcarlosdev** [comment] 2024-03-29 17:14
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Closed by mrcarlosdev** 2024-03-29 17:14 UTC

**Comment by Meertman** [comment] 2024-07-26 09:22
Added an idea to the APIM forum as recommended in the support ticket by Microsoft in order to be able to follow up on the status of this issue.
You can find the idea here: https://feedback.azure.com/d365community/idea/678a9f4b-304b-ef11-b4ad-000d3ae688a1
