### ISSUE TITLE
Some delegated actions lead to 404 errors

### ISSUE THREAD

**Issue by adamstruck** [Azure/api-management-developer-portal#926] opened 2020-09-17 20:40 UTC
## Bug description

Delegated actions such as "EditProfile", "ChangePassword" and "Signout" lead to 404 page not found errors. 

My delegation server uses Azure B2C for most user flows. 

## Reproduction steps

1. Sign in
2. Go to Profile
3. Click "Change name" or "Change password"
4. On delegated B2C flow page click "cancel". This redirects back to the profile page. 
5. Repeat step 3 and you end up with "Page you're looking for doesn't exist". In the inspector I see the following request return a 404: `GET https://xxxxxx.developer.azure-api.net/delegation-changeProfile?userId=xxxx`.

## Expected behavior

The above actions should always work. 

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: MacOS Catalina
 - Browser: Google Chrome
 - Version: 85.0.4183.102

**Comment by azaslonov** [comment] 2020-09-18 16:35
Hi Adam, yep, looks like a bug, we'll take care of it. Thanks.

**Comment by adamstruck** [comment] 2020-09-18 17:12
Can you provide an estimated timeframe for a fix? This appears to be the last blocker preventing my organization from adopting the new portal. Thanks.

**Comment by azaslonov** [comment] 2020-09-18 17:18
I'll see if this can be included in next week's release, worst case the week that follows.

**Comment by adamstruck** [comment] 2020-09-28 17:25
Any updates on this?

**Comment by azaslonov** [comment] 2020-09-29 18:02
Hi Adam, sorry for the delay, just got to it, looks like we would need a network trace. Could you please capture the whole process into HAR file and send it to apimportalfeedback@microsoft.com?

**Comment by adamstruck** [comment] 2020-09-29 18:35
@azaslonov I sent the HAR to the email address you provided.

**Comment by azaslonov** [comment] 2020-09-30 03:59
Thanks Adam, as I mentioned offline, we found and fixed the issue on our backend. It will take 2-3 weeks to deploy. I'm closing this issue for now.

**Closed by azaslonov** 2020-09-30 03:59 UTC
Labels: P1, bug

**Comment by adamstruck** [comment] 2020-10-14 18:59
Still waiting on the fix to be deployed. Any updates or am I still looking at another week or so?

**Comment by azaslonov** [comment] 2020-10-14 19:10
Sorry Adam, yes, I was pretty sure it's been in the last release :( so yeah, another week or so.

**Comment by eskour** [comment] 2023-09-05 10:59
It still is not fixed. I can reproduce the issue as of today (5 Sep 2023).

**Comment by eamreyes** [comment] 2024-03-19 18:26
Can confirm I'm experiencing this issue. March 19th 2024.

May have been a regression when fixing this bug? 

https://github.com/Azure/api-management-developer-portal/issues/2155
