### ISSUE TITLE
New Dev Portal: API Spec details not visible

### ISSUE THREAD

**Issue by kanwarnitin** [Azure/api-management-developer-portal#1291] opened 2021-04-30 10:17 UTC
## Bug description

New developer portal is unable to synchronize API spec details from APIM (internal VNET).
Spec for none of the API we've setup is visible on Dev portal. Only API name and operation name visible on left pane.
Try it section keeps spinning/waiting

## Reproduction steps

1. Access APIM from a machine connected to corporate network
2. Setup new API (Sales Order Service; suffix: soservice) in APIM using OpenAPI3 or manually and save.
2. On Azure Portal, go to APIM > Developer Portal > Portal overview
3. _Publish the portal_ section has warnings and Publish button is disabled

![image](https://user-images.githubusercontent.com/36647773/116681058-5cb49000-a9a4-11eb-9227-550433e93154.png)

![image](https://user-images.githubusercontent.com/36647773/116679806-df3c5000-a9a2-11eb-9422-d5c607e5b767.png)

_Try publish from Developer portal_
4. Open Developer portal in management mode, go to Operations (plane icon) and click _Publish website_
5. Open the Developer portal in another browser window in _incognito_ mode
6. Login to developer portal using username and password
7. Go to APIs and click on new API
8. No permalink/URL visible after the verb POST, Request body section is blank, Response headers is blank, Definitions section is blank
9. Click on Try it button -> Keeps spinning and doesn't move forward

![image](https://user-images.githubusercontent.com/36647773/116680035-20346480-a9a3-11eb-8efd-6e1cf0de70ab.png)

_Try Echo API and then try new API_
10. Select Echo API from dropdown -> Request URL is displayed correctly. Try it also functions
11. Go to your new API and select an operation
12. Permalink/URL is now visible after verb POST, Request body, Response Headers and Definitions are also visible
13. URL is incorrect showing suffix as _echo_ instead of soservice
14. Try it section shows details but HTTP request URL is incorrect (showing echo suffix)
![image](https://user-images.githubusercontent.com/36647773/116680670-dac46700-a9a3-11eb-83f1-89898e69d021.png)

_Reset the Dev portal and republish_
15. Problem persists

## Expected behavior

API specification should be visible and information should match to setup in APIM

## Is your portal managed or self-hosted?

Managed

## API Management service name

gc-apim-dev1

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome, Edge
 - Version: Chrome Version 90.0.4430.93, Edge Version 90.0.818.49

## Additional context

APIM hosted in internal VNET and only accessible from corporate network
Dev portal also only accessible from corporate network

**Comment by aquasheep20** [comment] 2021-05-02 14:31
I have the same issue.  Exporting in openapi 3 format and re-importing with new name seems to resolve it.  The original api errors still persist.

**Comment by ygrik** [comment] 2021-05-06 23:21
@kanwarnitin, @aquasheep20
I can't reproduce this issue. Also, I can't check your portal because it in VNET.
Could you please provide web console traces (.har) to apimportalfeedback@microsoft.com

**Comment by azaslonov** [comment] 2021-05-12 21:30
Closing this issue because that's not the developer portal codebase issue, and we're following up on this offline.

**Closed by azaslonov** 2021-05-12 21:30 UTC

**Comment by kanwarnitin** [comment] 2021-05-17 21:32
We have found that API spec is only visible on Dev Portal after we also include "Managed" gateway in API settings. Earlier, only the self-hosted gateway "gc-apim-dev1" was setup as gateway for the API. We do not intend to use "Managed" gateway though in the final solution.

- Now we're able to invoke internal (private) API from Dev portal while connected to corporate network
- Also we're able to invoke same API from postman. We don't need to use hostname of self-hosted gateway in API endpoint URI; hostname generated by azure is working: --> https://gc-apim-dev1.azure-api.net/soservice/salesordersearch
- However, "Test" from APIM is not working. Hence console trace is not generated. Below is the error message
```
Request:
POST https://gc-apim-dev1.azure-api.net/soservice/salesordersearch HTTP/1.1
Host: gc-apim-dev1.azure-api.net
Content-Type: application/json
Ocp-Apim-Subscription-Key: •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ocp-Apim-Trace: true

Response:
HTTP/1.1 400 Bad Request
content-length: 82
content-type: application/json
vary: Origin
{
    "error": "The remote name could not be resolved: 'gc-apim-dev1.azure-api.net'"
}

!Trace
Trace is not available because response does not contain Ocp-Apim-Trace-Location header.
```

**Comment by mikebudzynski** [comment] 2021-05-18 19:27
@kanwarnitin, could you please clarify the problems here? I have checked that APIs exposed through self-hosted gateways only appear correctly in my developer portal.

Is the error above coming from the Azure portal test interface or from the developer portal's interactive console?

**Comment by kanwarnitin** [comment] 2021-05-23 13:02
@mikebudzynski Mike, Above error is from APIM Test interface.

**Configuration:**
1. APIM in VNET
2. Managed Dev Portal
3. API Gateway is self-hosted on-prem
4. Backends are on-prem

**Problems** when only "gc-apim-dev1" is used as gateway in API setting:
1. API spec is doesn't get published on managed dev portal. Only API name and operation names are visible.
2. Try it functionality shows blank panel and 3 dots stays on the panel 
3. Test interface on APIM doesn't work either. Throws 400 error: The remote name could not be resolved: 'gc-apim-dev1.azure-api.net'

_What is functional?_
1. We're able to invoke API endpoints when we use domain name of self-hosted gateway. This means that APIM is able to synchronize with self-hosted gateway

**Problems** when both "Managed" and "gc-apim-dev1" are used as gateways in API settings:
1. Test interface on APIM doesn't work either. Throws 400 error: The remote name could not be resolved: 'gc-apim-dev1.azure-api.net'

_What is functional?_
1. API spec gets published on managed dev portal successfully and all information is visible
2. Try it functionality also works fine and returns 200 OK

**Desired capabilities:**
1. Managed dev portal to be used for both internal (corporate) and external (trusted partners) users
2. APIs published to internal products should have internal domain name on API URL on Dev portal (not gc-apim-dev1.azure-api.net) so that internal developers use correct endpoint URL and traffic originating from internal services stays within corporate network. Currently, it is always https://gc-apim-dev.azure-api.net/...)
3. APIs published to external products should have external domain name on API URL on Dev portal so that external developers use correct endpoint URL
4. Both internal and external users/developers should be able to try the API operations from managed dev portal
5. Not to use Managed API gateway

![Target Arch](https://user-images.githubusercontent.com/36647773/119261431-4e3a4c80-bbcf-11eb-99c1-ab583f5bf724.JPG)

**Comment by mikebudzynski** [comment] 2021-05-25 17:31
> API spec is doesn't get published on managed dev portal. Only API name and operation names are visible.

What do you mean by the API spec not being published? Is the API reference page empty? Could you send screenshots or a short recording to apimportalfeedback@microsoft.com?

> Try it functionality shows blank panel and 3 dots stays on the panel

I was able to reproduce this issue, but my self-hosted gateway isn't exposed through a domain. Have you assigned a custom domain to your self-hosted gateways?

> Test interface on APIM doesn't work either. Throws 400 error: The remote name could not be resolved: 'gc-apim-dev1.azure-api.net'

Do you have connectivity to the self-hosted gateway from your local machine? Make sure to select the option "Bypass CORS proxy".
