### ISSUE TITLE
Enumerations not shown

### ISSUE THREAD

**Issue by GuillaumeRP** [Azure/api-management-developer-portal#670] opened 2020-06-02 13:58 UTC
On Dev Portal, when API details are shown, enumerations are not presented, while they are in the downloadable JSON file.

**Comment by azaslonov** [comment] 2020-06-04 17:34
Hi @GuillaumeRP, enumerations are supported, probably, there is a specific case that you have. Can you post the schema here?

**Comment by mikebudzynski** [comment] 2020-06-16 17:33
Closing the issue due to lack of reproduction steps.

**Closed by mikebudzynski** 2020-06-16 17:33 UTC
Labels: response-needed
