### ISSUE TITLE
API Developer Portal does not show contact information provided in OpenAPI specification

### ISSUE THREAD

**Issue by eXXL** [Azure/api-management-developer-portal#1440] opened 2021-09-06 18:12 UTC
## Bug description

The API Portal does not display contact information provided in the OpenAPI specification.

## Reproduction steps

Create an API based on an OpenAPI specification with contact information:

```
openapi: 3.0.1
info:
  title: Echo API
  version: '1.0'
  contact:
    name: My Name
    url: 'mailto:myname@email.com'
```

## Expected behavior

When I open the API description on the /api-details page of the Developer Portal, I want to see a "Contact" section showing both name and URL values.

## Is your portal managed or self-hosted?

Managed

## Additional context

We believe that contact details are important so the developers are able to contact the person or team who is responsible for it in case they have questions or wishes. On the other side, the API providers will take care of their APIs descriptions quality if their name is on it.

**Comment by mikebudzynski** [comment] 2021-09-07 18:01
Duplicate of #997

**Closed by mikebudzynski** 2021-09-07 18:01 UTC
Labels: (t) Improvement, P1, (u) OpenAPI + API ref
