### ISSUE TITLE
Passing tags to filter by as URL parameters for the list of APIs and list of API operations widgets is not working

### ISSUE THREAD

**Issue by ncroad** [Azure/api-management-developer-portal#1665] opened 2022-02-21 22:05 UTC
Are we able to confirm that this functionality is still working as expected? If the appropriate thing is to raise a defect or issue, please let me know.
When you add a filter manually on the api list page, it works fine. If you refresh the page, or navigate to the page with the tag filter it doesn't filter the list 100% of the time, actually it is very hard to get it to work.

We had this previously working late last year, early this year, but it appears now that it is intermittent and in same cases the second API call that includes the tags as a query string parameter doesn't always fire. 
Where we have seen it working the 2nd api call with tags, has only been when it completes after the first call for the list of apis. If it completes before the one with the tags it appears to show the full list.  We are using the noted URL format above. 
API calls I am referring to from the portal are: 
https://xxxxxxxxxxx/subscriptions/000/resourceGroups/000/providers/Microsoft.ApiManagement/service/apim-instance-xxxxx/apis?expandApiVersionSet=true&$top=50&$skip=0&$filter=isCurrent%20eq%20true&api-version=2021-04-01-preview
vs: 
https://xxxxxxxxxxx/subscriptions/000/resourceGroups/000/providers/Microsoft.ApiManagement/service/apim-instance-xxxxx/apis?expandApiVersionSet=true&$top=50&$skip=0&tags[0]=TagXXXXX&$filter=isCurrent%20eq%20true&api-version=2021-04-01-preview

_Originally posted by @ncroad in https://github.com/Azure/api-management-developer-portal/issues/1189#issuecomment-1047225909_

**Comment by ncroad** [comment] 2022-02-22 03:09
Further to this, when we use the API Tiles control instead of the API List control, we don't even see the second request to get the list of apis mentioned above with the tags parameter included.

**Comment by mikebudzynski** [comment] 2022-02-25 21:47
@ncroad, I am not able to reproduce the issue. When I visit my developer portal at `https://<my-apim-service-name>.developer.azure-api.net/apis#tags=testtag` and refresh the page, I always get a list of APIs with `testtag`. Can you provide more precise reproduction steps? If you aren't able to do so, please contact Azure support for assistance and they will troubleshoot the issue.

**Comment by ncroad** [comment] 2022-02-26 07:21
@mikebudzynski , I've just sent an email with the steps to reproduce and recorded it using Problem Step Recorder. Hopefully that helps recreate it.

**Comment by azaslonov** [comment] 2022-03-04 01:42
The fix merged. We'll start a new release some time next week.

**Closed** 2022-03-04 01:41 UTC
Labels: Response needed

**Comment by ncroad** [comment] 2022-03-23 21:52
Hi team, are you able to provide an update on this defect please in particular when you expect to start releasing the fix? 
This has the potential to block a major production release for our client.

**Comment by mikebudzynski** [comment] 2022-03-23 22:05
@ncroad, the fix that is referenced above (for the tiles version of the widget) will be released in the next couple of weeks. We plan to investigate the other problem (around the double API call) within the next week or so. The fix will likely roll out in late April or in May.
