### ISSUE TITLE
Menu is broken in the Mobile and small size screen 

### ISSUE THREAD

**Issue by chaosity-io** [Azure/api-management-developer-portal#2394] opened 2024-02-04 13:06 UTC
Menu component is broken  for mobile and small screen 

## Reproduction steps

1. Setup new api portal as "contoso" and publish it.
2. Open the website in chrome browser. press F12 to go to console. 
3. In the developer tool select device as IPhone.
4. Click on the menu icon and a white screen fills the browser.

## Expected behavior

The same menu in vertical direction.

## Is your portal managed or self-hosted?

Managed and Self-hosted tag 25 and 24

## Release tag or commit SHA (if using self-hosted version)

[2.25.0] 23004639f1d486d5b620526f6bb9af31f2cce415
[2.24.0] 7977733f7fb282e5d95bbe754761853eb99f48fc

## API Management service name

chaosity-io

## Environment

 - Operating system: Ubuntu
 - Browser: Chrome
 - Version: latest

**Comment by malincrist** [comment] 2024-02-05 11:14
hi @chaosity-io , thank you for reaching out. This issue was fixed in 2.25. If you use the managed portal, release 2.25 was not deployed everywhere yet. Please give it a few more days to reach all the regions.

Please note that you should reset the content of the portal in order to get these changes, as mentioned in #2198:

> (only newly created websites).

Closing this as duplicate of #1783

**Closed by malincrist** 2024-02-05 11:14 UTC

**Comment by chaosity-io** [comment] 2024-02-05 12:54
To be clear this issue that I am showing in the attached image is fixed in 2.25?

![image](https://github.com/Azure/api-management-developer-portal/assets/131941272/c5787284-bcc2-45f6-9c94-7ae4538a9285)

**Comment by malincrist** [comment] 2024-02-05 13:10
I understand, yes it should be fixed in 2.25.
For me, for the self-hosted on version 2.25, it works (with reset content):
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/a256524c-103b-4fe5-8590-ea60bbf1268d)

**Comment by chaosity-io** [comment] 2024-02-05 13:14
Happy to see something in the white box. But It still needs to be adjusted.
All of those buttons must fill the top and the rest of the white box must
be removed.
