### ISSUE TITLE
Schemas in body with oneOf are not being rendered

### ISSUE THREAD

**Issue by markbriggs-ms** [Azure/api-management-developer-portal#1762] opened 2022-05-09 12:11 UTC
<img width="426" alt="image" src="https://user-images.githubusercontent.com/44032869/167406727-8a7b3e7d-764e-49a0-8eb0-6bd12109f217.png">

The response example below is not showing the scheme from the oneOf validation:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/44032869/167406829-0f52d73d-a323-45f9-af97-0b2d3b182197.png">

**Comment by azaslonov** [comment] 2022-05-10 22:54
@jsorohova, do we address this case by chance?

**Comment by markbriggs-ms** [comment] 2022-05-11 11:22
What additional info do you need from me?

Mark Briggs | Senior Program Manager | Microsoft Azure Engineering | FSI
Microsoft UK, Thames Valley Park, Reading, Berkshire, RG6 1WG, United Kingdom
m: +44 (0)7583695551 | e:  ***@***.******@***.***>
[Microsoft Colour - small]

**Advance notice of upcoming leave or extended travel/unavailability**
May 30th - 3rd June

**Comment by jsorohova** [comment] 2022-05-12 11:43
@markbriggs-ms It would help a lot, if you could provide your schema definition file. But overall the issue is clear, we will add it to the backlog. Thank you for reporting this.

**Comment by markbriggs-ms** [comment] 2022-05-12 12:03
Sent file privately

**Comment by jsorohova** [comment] 2022-07-19 09:43
The customer confirmed that the issue is fixed. Closing the ticket.

**Closed by jsorohova** 2022-07-19 09:43 UTC
Labels: (t) Bug, P1, (u) OpenAPI + API ref
