### ISSUE TITLE
validate-jwt policy changes disappear when saved

### ISSUE THREAD

**Issue by sujayathavale** [Azure/api-management-developer-portal#766] opened 2020-07-21 02:18 UTC
## Bug description

After saving policy validate-jwt policy, using newly released features in June release (https://azure.microsoft.com/en-gb/updates/azure-api-management-update-june-2020/), the UI does not appear to retain saved changes. Even though, under the hood the policy has been correctly applied.(verified via Azure Powershell)

## Reproduction steps
1. Go to policy editor view in in any API where you can edit policy XML
2. Replace with the following policy
` <policies>
    <inbound>
        <validate-jwt header-name="Authorization">
            <issuer-signing-keys>
                <key e="AQAB" n="pO2+BpARfKknqyr8sDRG1VmLlw5gBv518n2/LVyh16lMg2YUmDAmJCRX0BJQl0LytR5FIK0PTFDWAofguReR4OiLzQjiwKt9yFrnyslSYy74Ux4AdvkqC2Rv+nJ7NYaLIF3e/+gYrdK0buxpqZq+Hlh6Qugc/pYnxgODT59UllNGbKWVW3tlLxyxhj2KwzWpruhh/ECS1dq487u0ZAwgNPJw05Ku0ZMt9PET35Z4kr295ugxZl/nfdnfqu3lFBtbIoegtc2Rsok8YW0q91PeHOWMSu1B6PK4oZnEe3lcHRvCQzijG1SvBAAAzRdNZ6lgHsXS9XWyk/FyMcUhqImwOPOAzRtSUoDTafuBiefmB1+Rm1ypUM3PJxOrCP3qfImTmlmPE5AFMzg+oZqyUlh/kodWrfvIn2BbQ2BLWywghcUvUV1U6ipqNKh2D9Tg0853hO1KBOKcX2BJCZkr5zjg7NaYLC4nl/nn8DVqcjxoNghsH+a6IzwoPkcz/yAB8KmsNmCO9Ru9bjgl7xMbuAWAWVQqC4QY7VFYTW8W7Inc0e97mU4CJ5zwPw2DiVpjQD0anAWY1L+k61FCi93NKYhIQLw44ijIXbCdLaXjKxXu8FEkFW3hi1duxEIgqHve5TfHTddWi2xjVfl8X8vH4rDJIniBlQYeNVe/PvTRqjTHr2E="></key>
            </issuer-signing-keys>
        </validate-jwt>
        <base />
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies> `
3. Press Save button
4. Notices that the UI does not show changes you saved

## Expected behavior
UI should retain and show the changes you saved

## Is your portal managed or self-hosted?
Managed

**Comment by mikebudzynski** [comment] 2020-07-22 00:28
Thanks for reporting this, @sujayathavale We will investigate if it's a regression, but I will close this issue here since it's not developer portal related.

**Closed by mikebudzynski** 2020-07-22 00:28 UTC
