### ISSUE TITLE
OAuth that works in deprecated developer portal fails in new portal

### ISSUE THREAD

**Issue by pierslawson** [Azure/api-management-developer-portal#1536] opened 2021-11-22 16:23 UTC
I have configured an Identity Server 4 instance to be used by the developer portal. This works fine in the deprecated developer portal but when I try using the new portal I get an unauthenticated response from the backend API. Taking the generated Access Token and plugging it into Postman everything works fine. It is only the new Devloper Portal that has a problem passing the token to the backend API.

## Bug description

The issue is that our backend services specifically look in the Authentication header for the authentication scheme "Bearer" as per the specificatiom https://datatracker.ietf.org/doc/html/rfc6750 but the development portal uses the scheme "bearer". Therefore our backend reqjects the authentication token.

## Reproduction steps

1. Set up OAuth 2 in API Management
2. Have an API use OAuth 2
3. In new Development Portal use the "Try it" button
4. Authenticate
5. Check the request Authorization header about to be sent to your API which will be of the form "Authorization: bearer XYZ"

## Expected behavior

Authorization header about to be sent to your API should be of the form "Authorization: Bearer XYZ"

## Is your portal managed or self-hosted?

Managed

**Comment by mikebudzynski** [comment] 2022-02-08 21:51
Duplicate of #1338.

**Closed by mikebudzynski** 2022-02-08 21:51 UTC
Labels: (t) Bug, P1, (u) Test console
