### ISSUE TITLE
Publishing fails to generate index.html

### ISSUE THREAD

**Issue by itsenes** [Azure/api-management-developer-portal#574] opened 2020-04-07 14:49 UTC
## Bug description
npm run publish fails to generate the website static content "fully" - homepage (index.html) in website's root is missing

## Reproduction steps
1. cloned the repo locally
2. changed all config files
3. executed npm install and npm run successfully - the designer portal seems to be working fine
4. executed npm run publish and received an error "Unable to apply knockout bindings to a template: Error" and the index.html is missing from the dist\website folder - i also noticed the home (page) folder is missing

## Expected behavior
i guess the pusblish process shoudl have generated index.html file

## Is your portal managed or self-hosted?
Self-hosted

## Release tag or commit SHA (if using self-hosted version)
2.2.3

## API Management service name
i'd rather not disclose that info

## Aditional context
i've done no code alterations what so ever apart from the configuration files (config.design.json, ...)

any ideas ?

thank you in advance

**Comment by azaslonov** [comment] 2020-04-08 20:36
Hi @itsenes,  not sure what is going on, could you please copy the full error?

**Comment by itsenes** [comment] 2020-04-09 09:15
> Hi @itsenes, not sure what is going on, could you please copy the full error?

Hi! and thank you for taking the time.

during the publish process i noticed the following error : 

**Unable to apply knockout bindings to a template: Error**

which i think has to do with the fact that the site is not being published properly. below you may find output from the publishing process

Session started.
Publishing website...
Publishing page APIs: Changelog - Microsoft Azure API Management - developer portal...
Publishing page APIs: Details - Microsoft Azure API Management - developer portal...
Publishing page APIs: List - Microsoft Azure API Management - developer portal...
Publishing page Change password - Microsoft Azure API Management - developer portal...
Publishing page Confirm password - Microsoft Azure API Management - developer portal...
Publishing page Errors: 404 Page not found - Microsoft Azure API Management - developer portal...
Publishing page Errors: 500 Internal error - Microsoft Azure API Management - developer portal...
Publishing page Home - Microsoft Azure API Management - developer portal...
Publishing page NewHome - Microsoft Azure API Management - developer portal...
Publishing page Products: Details - Microsoft Azure API Management - developer portal...
Publishing page Products: List - Microsoft Azure API Management - developer portal...
Publishing page Reset password - Microsoft Azure API Management - developer portal...
Publishing page Sign in - Microsoft Azure API Management - developer portal...
Publishing page Sign up - Microsoft Azure API Management - developer portal...
Publishing page Sign up with OAuth - Microsoft Azure API Management - developer portal...
Publishing page Submit issue - Microsoft Azure API Management - developer portal...
Publishing page User: Profile - Microsoft Azure API Management - developer portal...
Publishing page User: Reports - Microsoft Azure API Management - developer portal...
Unable to apply knockout bindings to a template: Error
Publishing media hero-gradient.jpg...
Publishing media featured-1.jpg...
Publishing media featured-2.jpg...
Publishing media featured-3.jpg...
Publishing media logo-contoso-small.png...
Publishing media contoso-black.png...
Publishing media logo-horizontal-wide.svg...
Publishing styles...
Website published successfully.
DONE.

thanks and let me know if you need more info.

BR,

**Comment by itsenes** [comment] 2020-04-09 15:30
Hi @azaslonov , i'm posting again because i have an update on the issue.

We have two apim instances, the dev and the production gateways. All my tests were done against the dev instance which is configured with delegated authentication (to use our identity system - identity server 4 btw)  and we did publish the new developer portal version. 

Today i changed my configs to use the production apim instance and tried the publishing process against that instance (where we haven't setup the delegated auth feature nor published the developers portal) and it rendered all files correclty! does this give any clues ?

BR,

**Comment by KevinHale-Bentley** [comment] 2020-04-09 18:13
I also noticed that the content is not being fully published.  For now, I use the following Powershell script code to publish:

```
$storageConnectionString="DefaultEndpointsProtocol=<your-connection-string-here>"
Write-Host "publishing to $storageConnectionString"

npm run build-designer
npm run build-publisher

az storage blob upload-batch --source ..\dist\website --destination "`$web" --connection-string $storageConnectionString
az storage blob upload-batch --source ..\dist\designer --destination "`$web" --connection-string $storageConnectionString

```

That said, I still don't have this running.  I can only say that with this approach, at least I can see the content under the $web container, and I can verify that the index page attempts to load.

**Comment by azaslonov** [comment] 2020-04-09 19:35
Hi @itsenes, thanks for the update, but it still not very clear. Do you mind sending us your service name or captured data to apimportalfeedback@microsoft.com? We'll take it from there.

**Comment by azaslonov** [comment] 2020-04-09 19:40
Hi @KevinHale-Bentley, I assume you switched registration
from the file system
```ts
const outputBlobStorage = new FileSystemBlobStorage("./dist/website");
injector.bindInstance("outputBlobStorage", outputBlobStorage); 
```
to Azure blob storage
```ts
const outputBlobStorage = new AzureBlobStorage(outputSettingsProvider);
```
...and it doesn't work. Can you please describe what is going on, what error messages do you see, etc.

**Comment by KevinHale-Bentley** [comment] 2020-04-09 20:53
Actually, I was just following the "[Self hosting the portal](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal)" instructions.  I didn't see anything about switching the registration.  I got to step 4, Run the portal, and it didn't work.  From there, I started troubleshooting from the static site in my storage account.  Obviously, not all of the content had been uploaded from there.  Not seeing anything in the instructions about how to get index.html uploaded, I abandoned the instructions and dug through the code to figure out how to at least get me started.  I am only evaluating dev portal options right now, so I started going the quick and dirty route just to get far enough along for what I am evaluating.

**Comment by azaslonov** [comment] 2020-04-09 21:06
I see, sorry, I was thinking you do some modification to the publisher.

Ok, so looking at the commands you mentioned, you run just these two:
`npm run build-designer` - this one builds the designer
`npm run build-publisher` - this one builds the publisher

The publishing itself gets done with `npm run publish`, which will generate the website at `/dist/websites` (Step 6 of the instruction), then you do the upload itself (Step 7) with the command:
```sh
az storage blob upload-batch --source dist/website --destination $web --connection-string <account-connection-string>
```

It gets the entire website folder and pushes it to the blob storage.

Does this help?

**Comment by KevinHale-Bentley** [comment] 2020-04-09 21:47
I tried that before I wrote the script, but not all of the content was uploaded.  Specifically, the editors folder and the index.html & page.html files were missing.

To be honest, while I am trying to make this a focal point of my work starting this week.  Instead I have been handling issues and shepherding deployments.  Once things settle down, I should go back to the beginning and try this all again.  On the plus side, digging in the way that I have has provided some more familiarity with the inner workings.  :)  Long-term, we plan to integrate our 3rd-party developer OIDC portal (based on Angular) with the APIM portal.  Part of my current work is to recommend whether we add APIM functionality to the existing OIDC portal; migrate the OIDC functionality into this dev portal; or, as my boss inquired, "start from scratch" (shudder).

**Comment by itsenes** [comment] 2020-04-10 11:42
@KevinHale-Bentley i would really like to know which way you'll decide to go - i'm refering to "add APIM functionality to the existing OIDC portal; migrate the OIDC functionality into this dev portal;"

BR,

**Comment by azaslonov** [comment] 2020-04-10 19:20
@itsenes  to make it work can you please add `backendUrl` to your `config.publish.json` like this:
```json
{
  "managementApiUrl": "https://chaniabank.management.azure-api.net",
  "managementApiVersion": "2018-06-01-preview",
  "managementApiAccessToken": "SharedAccessSignature ...",
  "blobStorageContainer": "content",
  "blobStorageConnectionString": "DefaultEndpointsProtocol=...",
  "environment": "publishing",
  "backendUrl": "https://chaniabank.developer.azure-api.net",
  "useHipCaptcha": false
}
```

Looks like we’re missing proper error message for this case.

**Comment by azaslonov** [comment] 2020-04-10 19:28
Hi @KevinHale-Bentley, first of all, all you need to publish to the blob is `/dist/website`. For instance, `page.html` is part of the designer, you probably don't need that.

Also, please feel free to reach me if you need any assistance with the setup, but we'll need specific errors and/or reproduction steps to help you, which I'd be glad to do.

**Comment by azaslonov** [comment] 2020-04-10 19:39
I'm closing this issue for now. Shall you need further assistance please feel free to reopen it or email us to apimportalfeedback@microsoft.com. 

We'll be adding respective pieces of documentation to cover this case.

**Closed by azaslonov** 2020-04-10 19:39 UTC
Labels: question

**Comment by KevinHale-Bentley** [comment] 2020-06-05 14:06
@itsenes, we have decided to use this portal in the self-hosted option so that we can add additional functionality to it.
