### ISSUE TITLE
No example for request body when the request body is an array.

### ISSUE THREAD

**Issue by VincentYan2018** [Azure/api-management-developer-portal#558] opened 2020-03-27 11:09 UTC
When a request body is an array for the api, the request body don't show the example set for it. 
The legacy portal shows the example and schema like this:
<img width="955" alt="old_portal_example" src="https://user-images.githubusercontent.com/21144447/77750189-55fb7100-705e-11ea-8354-f20cec3b1203.png">
<img width="960" alt="old_portal_schema" src="https://user-images.githubusercontent.com/21144447/77750212-60b60600-705e-11ea-8855-2e7741216e9a.png">
But the new portal won't show the example when the request body is an array:
<img width="762" alt="new_portal" src="https://user-images.githubusercontent.com/21144447/77750282-74fa0300-705e-11ea-85d1-f33ebe31eda4.png">

**Comment by azaslonov** [comment] 2020-03-31 18:32
Hi @VincentYan2018, the legacy portal pre-generates examples for you, and the new one uses whatever you provide as an example (due to flexibility and performance considerations). You can provide your own or generate it as well if you'd like to:

![image](https://user-images.githubusercontent.com/2320302/78062149-188b3200-7343-11ea-88a6-d88a868ffb6c.png)

**Comment by michaeltnguyen** [comment] 2020-03-31 18:51
Hi @azaslonov , the challenge is that when we import swagger documents, it will override any custom examples we have.  And it's cumbersome to manually update the examples every time we re-import.

**Comment by VincentYan2018** [comment] 2020-04-01 01:45
Hi @azaslonov, I know where I should set example. The problem is that when a definition is an array and I set example for it, the new portal won't show the example. But when you access the legacy portal, it show the example. You can see in the last comment, it is a same api, and I already set the example.

**Comment by azaslonov** [comment] 2020-04-01 16:16
Indeed, I could repro the issue. We'll fix that.

**Comment by jason-runzer** [comment] 2020-05-28 17:32
It seems like this is also an issue for the response examples. Is there an eta on the fix for this issue? @azaslonov

**Comment by mluker** [comment] 2021-02-28 21:57
I am having the same issue, is this just how it works or is this a bug?

**Comment by CoHealer** [comment] 2021-03-22 21:13
It's a bug and it shouldn't be labelled as usability. This bug is a year old and marked as a P1. Are you only fixing P0 issues at this point?

**Comment by mikebudzynski** [comment] 2021-03-22 21:58
> It's a bug and it shouldn't be labelled as usability.

I updated the label.

> Are you only fixing P0 issues at this point?

There are no P0 issues at this moment and we're focused on fixing P1 items as well as rolling out support for new features. You can see what's coming up next in the Backlog project: https://github.com/Azure/api-management-developer-portal/projects/5 Release notes in the release section of the repository list all the fixes and features we've been rolling out.

**Comment by jsorohova** [comment] 2022-01-20 17:15
Hello @VincentYan2018, can you please check if this is still reproducible? We fixed an array displaying but I would like to double-check this issue with you. Thank you.

**Comment by jsorohova** [comment] 2022-05-12 11:25
Closing this issue as fixed.

**Closed by jsorohova** 2022-05-12 11:25 UTC
Labels: (t) Bug, P1, (u) OpenAPI + API ref
