### ISSUE TITLE
Mandatory query parameters shown as template parameters when created from OpenAPI specification

### ISSUE THREAD

**Issue by Kumar-Ashwin-Hubert** [Azure/api-management-developer-portal#1241] opened 2021-04-12 11:00 UTC
## Bug description

Setting a required "Query" parameter in OpenAPI is getting set as "Template" parameter in Azure APIM.

## Reproduction steps

1. In the below OpenAPI sample, `id` has been marked as a required parameter in query : 
![image](https://user-images.githubusercontent.com/25590394/114359107-44193d00-9b91-11eb-8e2b-1b47d98454cd.png)
2. On save of the OpenAPI spec, the mandatory query param is getting mapped to template param.
![image](https://user-images.githubusercontent.com/25590394/114359680-da4d6300-9b91-11eb-95cf-3f2b34422878.png)
3. The main issue is that if the end user doesn't provide an `id` in this above example, they would get a 404 resource not found without any additional info instead of a 400 Bad Request.

## Expected behavior
Mandatory query parameters in OpenAPI spec should be created as mandatory query parameters and not template parameters. 
This behavior is happening if the api is created manually using the "Add operation" (without from OpenAPI spec).

## Is your portal managed or self-hosted?
Managed

**Comment by mikebudzynski** [comment] 2021-04-13 22:48
Cross-referencing #1221

**Comment by azaslonov** [comment] 2021-04-19 18:30
We have scheduled a work item for the Azure portal team, ETA is around 3 weeks.
I'm closing this issue because it's not related to the Developer portal project.

**Closed by azaslonov** 2021-04-19 18:30 UTC
Labels: (t) Bug, (u) OpenAPI + API ref, P1

**Comment by Kumar-Ashwin-Hubert** [comment] 2021-04-22 07:19
@azaslonov can you please share in the work item link that you created for the Azure Portal team, so that I can track it.

**Comment by mikebudzynski** [comment] 2021-04-22 17:27
It's not publicly available.

**Comment by Kumar-Ashwin-Hubert** [comment] 2021-05-12 08:01
@mikebudzynski can you please share in any update on this ? ETA mentioned earlier was around 3 weeks.

**Comment by mikebudzynski** [comment] 2021-05-13 23:00
@Kumar-Ashwin-Hubert, the fix will be included in the next API Management service release in June and we expect it to fully roll out in July. You can monitor this GitHub site for the release notes: https://aka.ms/apim/releases Apologies for the confusion.

**Comment by Timico05** [comment] 2022-01-26 15:41
As far as I understood the bugfix should have been rolled out.
But we still experience this issue in Azure Portal API Management.
Please clarify if that bugfix really had effect on that issue.

![image](https://user-images.githubusercontent.com/69272352/151195213-7194b6fb-7456-4095-87b6-cde2493f4a6d.png)
![image](https://user-images.githubusercontent.com/69272352/151195602-ccdaa3a7-6a86-45c0-8b43-938f8b54726a.png)

**Comment by Kumar-Ashwin-Hubert** [comment] 2022-01-28 05:38
Same here as well @mikebudzynski, the issue is still open after 8 months.

**Comment by fballan93** [comment] 2023-06-14 11:01
any update for this bug ?

**Comment by del77** [comment] 2023-06-27 12:55
It still happens, is there any update on this?

**Comment by HimanshuKapoor328** [comment] 2024-06-27 06:05
Same issue i am facing in apim when i am going to upload api.yaml file via openAi  spec. using APIOPS.

![image](https://github.com/Azure/api-management-developer-portal/assets/99945833/d335df66-ba14-4662-960a-90aedfd75c92)


Is there any way to control that option using APIOPS??

**Comment by mohitsinha-thbs** [comment] 2024-07-17 10:59
The issue is still happening, did anyone found any workaround rather than editing it from ui?
