### ISSUE TITLE
Menu-widget setting disabling whole page

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1120] opened 2021-01-18 07:59 UTC
## Bug description

"Show page headings" setting in the menu item is disabling a page and furthermore preventing to add this element to the page.

The first encounter with the bug was when one page wasn't loading in the editor mode. I would just get the error message and a blank screen. One could not access this page at all. It was impossible to find a solution in the editor itself (because the page was inaccessible).  After making some diffs I found out that there was an Issue with the Menu item and the "Show page headings" setting. To keep working with this page I had to upload an older Version of the portal, where the page was still working or download a new backup with the corrupt JSON and manually remove the corrupt section. Here: the block with the menu-widget. Only after that one can continue working on this page. While testing there have been some inconsistencies. For example at first I couldn't select the setting of the menu item without getting the error. After a few tries (and inserting it at different points of the page) it worked perfectly normal on this page. For further testing I re-uploaded the version where I started testing and even while trying the exact same tests it doesn't work again. Meaning the error message is thrown again.

Since I couldn't make sense of the situation, the portal and the JSON (where nothing seems wrong) I'm not sure why and how this occurs. If this would happen more often it could lead to data loss.
The error seems to occur only on certain pages. I can provide the JSON/Service name via email.

## Reproduction steps

1. Create new Section on the affected page
2. Add a menu item
<img width="674" alt="NavigationIssue02" src="https://user-images.githubusercontent.com/58420097/104583474-76360400-5661-11eb-8615-fffb01c5f720.PNG">

3. Select "Show page headings"
<img width="813" alt="NavigationIssue03" src="https://user-images.githubusercontent.com/58420097/104583653-abdaed00-5661-11eb-9f88-3c4bae895611.PNG">

4. Error pops up

## Expected behavior

 1. Find the source of this behavior and fix it
 2. Even when the page is disabled with an error like this provide an undo button in the editor.
 3. More precise Error messages would help find the Issue. "Oops! Something went wrong" sometimes lacks information and depth. This would greatly increase the chance to fix this issue.

## Is your portal managed or self-hosted?

 Managed

**Comment by azaslonov** [comment] 2021-02-14 17:47
@ZarTrox, I still cannot reproduce this issue. Is there anything else you can share? Maybe you have that JSON with a broken page by chance?

**Comment by mikebudzynski** [comment] 2021-03-22 18:51
Fixed in release 2.7.1: https://github.com/Azure/api-management-developer-portal/releases/tag/2.7.1

**Closed by mikebudzynski** 2021-03-22 18:51 UTC
Labels: (t) Bug, (u) Customization, (u) Paperbits, P0
