### ISSUE TITLE
Internet Explorer 11 is a broken experience showing menu items that shouldn't be rendered. 

### ISSUE THREAD

**Issue by VWACBrick** [Azure/api-management-developer-portal#722] opened 2020-06-24 00:47 UTC
## Bug description

Internet Explorer 11 (IE11) is a very bad experience.  I realize it's an old browser that is no longer used, but maybe the site should display a "your browser is not supported" banner by default. More worried about the rendering of menu items that shouldn't be shown in a non logged in state. 

Maybe provide a link to download the new Microsoft Edge browser for a better experience

## Reproduction steps

1. Open the new portal (default layout) in IE 11
2. Site will render poorly.
![image](https://user-images.githubusercontent.com/65634611/85482934-bd9b5c80-b578-11ea-9d59-47a3460e1579.png)

3. site thinks the user is **signed in** and the Profile link is active. 
![image](https://user-images.githubusercontent.com/65634611/85483363-837e8a80-b579-11ea-8b97-6212324af09e.png)

4. API page is blank

## Expected behavior

Maybe have built into the site "your browser is not supported" banner.  
Also, UI elements should not be showing as if the user is logged in.

## Is your portal managed or self-hosted?

Self-hosted 

Release 2.3.0

## API Management service name

Default Contoso site

## Environment

 - Operating system: Windows 10
 - Browser: Internet Explorer 11
 - Version: 11.0

## Additional context

Our company IT department still has IE 11 the default browser for their new PC images because of legacy internal systems.

**Comment by mikebudzynski** [comment] 2020-06-24 15:07
The list of supported browsers is documented here: https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal#whats-the-browser-support-for-the-portal

Good point about displaying a banner if the browser isn't supported.

**Comment by VWACBrick** [comment] 2020-06-24 15:33
Yes, I agree. The browser is too old to be supported. The banner would a nice touch.

However, I also think the failed state in old browsers should look like the user is not logged in.

**Comment by lrtico** [comment] 2020-06-29 18:57
I've been trying to implement a client-side IE detection script that adds a class to the body which hides/shows the app/message. It is working locally but not when deployed to staging.

[Here is a screenshot]( https://preview.eastwestbank.com/bridgeblastresources/ie-detection-screenshot.jpg).

The problem is the IE detection script is blocked by a syntax error in the theme.js.  Any thoughts on how might we show a message before IE tries to execute the compiled portal JavaScript?

**Comment by lrtico** [comment] 2020-07-23 18:40
@VWACBrick I implemented a temporary solution by adding inline JS <script> to the head tag directly under the <meta> tags of the page.html file (\node-modules\@paperbits\core\publishing\page.html). 

You can see it here: https://apimstaticweb.z5.web.core.windows.net/

**Comment by shashiguru** [comment] 2020-07-28 11:52
Hi @VWACBrick , sorry to spamming here, i need help to move from managed version to self hosted without losing implementation done through managed version. as your working on self hosted so what exact way your using for self hosted and your answers will be appreciated and thanks advance.

**Comment by VWACBrick** [comment] 2020-07-28 15:21
@shashiguru It's a little off topic in this post, but you can find the information about moving from Managed to Self-Hosted in this wiki
[https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-3-provision-the-default-template](https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal#step-3-provision-the-default-template)

**Comment by azaslonov** [comment] 2021-04-23 00:56
I guess we can close this issue.

**Closed by azaslonov** 2021-04-23 00:56 UTC
Labels: (t) Improvement, (u) Usability, P1

**Comment by lrtico** [comment] 2021-04-23 20:58
Hi Alexander, thank you for replying! Yes, I think the issues I opened for
East West Bank's portal can be closed if you don't see the portal anymore.
:)
