### ISSUE TITLE
Support for Use Authorization Code Flow with PKCE instead of Implicit Flow - interactive console

### ISSUE THREAD

**Issue by saikiran-karumuri-by** [Azure/api-management-developer-portal#1146] opened 2021-02-10 21:39 UTC
Hello Team, Is there any support for Authorization Code Flow with PKCE instead of Implicit Flow - interactive console ??

**Comment by azaslonov** [comment] 2021-02-10 21:52
Hi @saikiran-karumuri-by, there is no support for PKCE currently, but we're planning to add it. I don't have ETA right now though.

**Comment by mikebudzynski** [comment] 2021-11-10 22:38
Closing this issue as a duplicate of #1142

**Closed by mikebudzynski** 2021-11-10 22:38 UTC
Labels: (t) Feature request
