### ISSUE TITLE
Authenticate with OAuth in the interactive developer console

### ISSUE THREAD

**Issue by mikebudzynski** [Azure/api-management-developer-portal#208] opened 2019-10-15 17:17 UTC

**Comment by sk-bln** [comment] 2019-11-08 13:14
Is this the same issue that in my case prevents AAD authentication when accessing the managed Developer Portal?

**Comment by mikebudzynski** [comment] 2019-11-22 23:06
@sk-bln No, it's authentication with OAuth credential in the interactive developer console.

**Comment by techports** [comment] 2019-12-02 07:57
OAuth selection is missing in new developer portal console whereas old developer portal had this feature.

**Comment by mikebudzynski** [comment] 2019-12-02 18:33
You can issue this issue for tracking the feature.

**Comment by TianyuHou** [comment] 2019-12-13 01:38
When can we have a GA version of this feature? Also can we contribute on this one?

**Comment by azaslonov** [comment] 2019-12-13 01:50
Hi Tianyu, ETA for this feature is 1/15.

**Comment by azaslonov** [comment] 2020-01-09 18:53
Updating ETA to 1/31. Looks like we won't make it by 1/15.

**Comment by mikebudzynski** [comment] 2020-02-07 19:38
Reference this issue from #56

**Comment by d3adz3r0** [comment] 2020-02-26 09:02
**Any news on the ETA ?** 
A few weeks ago @azaslonov mentioned the 01/31 (if i remember correctly). But its message was deleted and since then nothing.

**Comment by mikebudzynski** [comment] 2020-02-26 19:43
> Any news on the ETA ?
> A few weeks ago @azaslonov mentioned the 01/31 (if i remember correctly). But its message was deleted and since then: nothing.

Our plans slipped and I removed the comment to avoid confusion. We don't have an immediate ETA at this moment.

**Comment by mikebudzynski** [comment] 2020-02-27 19:44
New ETA is first half of April.

**Comment by SJThomas28** [comment] 2020-03-19 09:10
> New ETA is first half of April.

Is the new ETA of first half of April confirmed? This is a critical functionality for us and the ETA for this feature would determine whether we need to proceed with an alternate APIM tool. Appreciate a confirmation

**Comment by mikebudzynski** [comment] 2020-03-20 19:47
We're planning to start the rollout in the second half of April - I'll keep you updated if we stay on track. Apologies for the delay, the current situation with coronavirus has impacted a few processes.

**Comment by SJThomas28** [comment] 2020-03-21 00:54
> The functionality is already implemented and we're planning to start the rollout in the second half of April - I'll keep you updated if we stay on track. Apologies for the delay, the current situation with coronavirus has impacted a few processes.

Thank you Mike for the update. Yes understand the impact that the current situation has caused for all of us. Do keep us posted on the progress of this rollout.

**Comment by kennethdm** [comment] 2020-04-15 14:31
> The functionality is already implemented and we're planning to start the rollout in the second half of April - I'll keep you updated if we stay on track. Apologies for the delay, the current situation with coronavirus has impacted a few processes.

Nice to see this has been implemented already, any update on planned rollout?
Will the rollout be region-based, and if so, what's the timeline?

**Comment by mikebudzynski** [comment] 2020-04-15 15:15
> any update on planned rollout?

No updates at this moment. We expect to be able to start the release some time in May.

> Will the rollout be region-based

The rollout is indeed region-based and there may be a few days of a difference between regions.

**Comment by mploksvenningsen** [comment] 2020-05-12 06:21
Still no update on this?

**Comment by JCAMPOLPA** [comment] 2020-05-12 14:44
Hi guys,
Any news on the rollout ? Can EOW be OK for Europe region for example ?
Thx

**Comment by TianyuHou** [comment] 2020-05-12 21:12
any updates? our product has been waiting on this for almost 6 months.

**Comment by azaslonov** [comment] 2020-05-12 21:17
The release is in progress, but it is quite bumpy. We'll update this thread as soon as we have something to share.

**Comment by JCAMPOLPA** [comment] 2020-05-14 07:57
Hi Alexander
Good news - just one point: do we have soemthing to do in our side, like Republish portal ? Or is is transparent when in Managed mode ?
Also, is there any notification through Azure Portal ?
Thanks a lot, APIM rocks !

**Comment by butsona** [comment] 2020-06-02 08:48
Any update?

There doesn't seem to be any reference to the Token generation in the May update. i presume it is included.

https://azure.microsoft.com/en-us/updates/azure-api-management-update-may-2020/

**Comment by TianyuHou** [comment] 2020-06-03 17:06
Any updates?

**Comment by azaslonov** [comment] 2020-06-03 17:09
The release for the backend is finishing up today/tomorrow. After that, we start rolling out portal release with OAuth support.

**Comment by TianyuHou** [comment] 2020-06-09 03:06
Has this feature released in prod? we still didn't see that console in our portal

**Comment by FreBon** [comment] 2020-06-15 10:50
Can't see it in the new developer portal on my tenant, do I need to do any additional configuration from the "old" developer portal?

**Comment by dgrospelier** [comment] 2020-06-15 12:30
@azaslonov: how can we be aware that:

- We have the new backend version in a particular APIM instance? Is there something we can query (Management API for example) to have a release version and to correlate to the roadmap?
- Same question for the Dev portal: how do we know that we need to re-publish to have the latest version? Maybe there is a way to know that the published version is not the last one?

**Comment by TianyuHou** [comment] 2020-06-17 17:30
same question here, any updates?

**Comment by azaslonov** [comment] 2020-06-17 18:19
Hi everyone,

First of all the feature is out everywhere, please give it a try, but to enable it you'll need to republish the portal.

Respective callback resources for the flows:
/signin-oauth/code/callback/{authServerName}
/signin-oauth/implicit/callback
/signin-oauth/credentials/{authServerName}

We'll update the documentation shortly.

**Comment by dgrospelier** [comment] 2020-06-17 18:24
@azaslonov : this is good news. 
I tried to use it, after the re-publish, I have an Oauth option in the test console.
My Oauth Server is setup successfully in my APIM instance because it works fine in the test console of the legacy dev portal. But when I try to get a JWT token in the new dev portal (client credential flow), I have a blank popup page as you can see here below:
![image](https://user-images.githubusercontent.com/10268596/84935108-8b04e600-b0d8-11ea-9510-1227a1ecd804.png)

Do I need to create 2 separates OAuth servers in the APIM configuration with two different configurations?

**Comment by joostjanhuls** [comment] 2020-06-18 19:41
@azaslonov I am experiencing the same issue as @dgrospelier but then using the authorization code grant flow. It seems like after an authorization code has been fetched from the OAuth server, the callback endpoint (/signin-oauth/code/callback/{authServerName}) returns a HTTP 500 Internal Server Error.

**Comment by azaslonov** [comment] 2020-06-18 19:51
Hi @dgrospelier, yes, it looks like there is an issue with `code` and `client_credentials` flows for some of the customers, we're investigating.

Meanwhile, it would be helpful if you guys could tell us the regions your services are in?

**Comment by joostjanhuls** [comment] 2020-06-18 19:58
> Hi @dgrospelier, @joostjanhuls, yes, it looks like there is an issue with `code` and `client_credentials` flows for some of the customers, we're investigating.
> 
> 
> 
> Meanwhile, it would be helpful if you guys could tell us the regions your services are in?

West Europe

**Comment by dgrospelier** [comment] 2020-06-18 20:41
@azaslonov France Central

**Comment by FreBon** [comment] 2020-06-22 05:28
Got the same issue in North Europe using `client_credentials`, just the dialog with {}.

**Comment by praemium1** [comment] 2020-06-22 05:38
Same in Australia Southeast.

**Comment by dgrospelier** [comment] 2020-06-22 05:41
It is now working fine in France Central FYI.

**Comment by butsona** [comment] 2020-06-23 10:29
Does anyone have information about how to enable? We have reset the instance and still don't see the option (just subscription key box, which we don't use). Do we need to add the callback address to enable the feature?

we're hosting in UK South

any guidance would be great appreciated

**Comment by dgrospelier** [comment] 2020-06-23 14:33
@butsona: you need to:

- Configure the "Oauth 2" settings of your APIM instance (https://docs.microsoft.com/fr-fr/azure/api-management/api-management-howto-oauth2)
- Associate your API with this OAuth 2 server (https://docs.microsoft.com/fr-fr/azure/api-management/api-management-howto-oauth2#configure-an-api-to-use-oauth-20-user-authorization)

**Comment by butsona** [comment] 2020-06-23 15:46
@dgrospelier 

many thanks we are currently using OIDC which is working for token retreiveal from the legacy portal. i presume this would also be included, not just the OAuth2 provider. Is this correct?

**Comment by nimccoll** [comment] 2020-06-25 13:11
I am testing out the new OAuth2 support in the new developer portal. My OAuth2 provider is Okta. I have updated all of the redirect URIs in Okta as required for the new Developer portal. The Client Credential flow works fine. However, I am getting the following error when using the Authorization Code flow - "The authentication request has an invalid 'state' parameter". This error is coming from the /signin-oauth/code/callback/ of the developer portal. The flow works fine in the legacy Developer portal. Any thoughts?

**Comment by bakintunde** [comment] 2020-06-26 18:24
> I am testing out the new OAuth2 support in the new developer portal. My OAuth2 provider is Okta. I have updated all of the redirect URIs in Okta as required for the new Developer portal. The Client Credential flow works fine. However, I am getting the following error when using the Authorization Code flow - "The authentication request has an invalid 'state' parameter". This error is coming from the /signin-oauth/code/callback/ of the developer portal. The flow works fine in the legacy Developer portal. Any thoughts?

You might need to uncheck "Support State Parameter" in the OAuth2.0 configuration. Under the OAuth2.0 tab for the APIM instance

**Comment by nimccoll** [comment] 2020-06-26 19:48
@bakintunde I have tried it with the Support State Parameter both checked and unchecked and the result is the same error. Any other ideas?

**Comment by bakintunde** [comment] 2020-06-26 20:29
> @bakintunde I have tried it with the Support State Parameter both checked and unchecked and the result is the same error. Any other ideas?

Did you and re-publish the portal after unchecking it?

**Comment by bakintunde** [comment] 2020-07-06 14:32
Hi @azaslonov,

Have the issues with OAuth2.0 for the new developer portal been resolved?
When can we expect the documentation to be updated?

Thanks

**Comment by chinmayv84** [comment] 2020-07-08 03:41
Hi @azaslonov,
Portal is republished and OAuth2 is configured as per https://github.com/Azure/api-management-developer-portal/wiki/Configuring-OAuth-2.0
But my redirect url is looks like https://contoso/docs/services/AAD/console/oauth2/authorizationcode/callback

If I use try-it feature with authorizationcode I get 404 error for url https://contoso/signin-oauth/code/callback/AAD?code=

**Comment by azaslonov** [comment] 2020-07-09 18:52
Hi @chinmayv84, we'll need to update official docs, but for now please refer to URLs described [here](https://github.com/Azure/api-management-developer-portal/wiki/Configuring-OAuth-2.0).

**Comment by chinmayv84** [comment] 2020-07-09 20:18
Hi @azaslonov, I am referring same documentation. I see redirect url is different on my apim instance, also redirect url field is readonly.

**Comment by vinoth12988** [comment] 2020-07-30 11:48
hi @azaslonov, Stil APIM in US West & US EAST doesn't give the new developer portal redirect URI as mentioned in the shared documentation https://github.com/Azure/api-management-developer-portal/wiki/Configuring-OAuth-2.0

This is an important & basic security feature for developer portal. Please can you update the status ASAP.

**Comment by vinoth12988** [comment] 2020-07-30 14:19
Finally worked for me!! If anyone still facing issue with New dev portal - OAUTH , Please use the redirect url for new dev portal in below format..

https://APIMNAME-apim.**developer**.azure-api.net/signin-oauth/code/callback/**{OAUTH Server name}**

**Comment by matsisak** [comment] 2020-08-19 12:04
Hi,
I receive this error message in the dialog when requesting the authorization code. Using ADFS as provider.
{"error":"invalid_request","error_description":"MSIS9692: Received invalid OAuth request. The Basic Authorization header must have ClientID and ClientSecret UrlEncoded then separated by ':'."}

Any ideas?

**Comment by matsisak** [comment] 2020-08-28 11:28
> Hi,
> I receive this error message in the dialog when requesting the authorization code. Using ADFS as provider.
> {"error":"invalid_request","error_description":"MSIS9692: Received invalid OAuth request. The Basic Authorization header must have ClientID and ClientSecret UrlEncoded then separated by ':'."}
> 
> Any ideas?

To add more details, the same Client Id and secret works for OAuth in the old developer portal. 
Seems you have to urlencode the clientid and secret:  https://github.com/elastic/elasticsearch/issues/43709

**Comment by shanemcnallie** [comment] 2020-09-22 19:38
> I am testing out the new OAuth2 support in the new developer portal. My OAuth2 provider is Okta. I have updated all of the redirect URIs in Okta as required for the new Developer portal. The Client Credential flow works fine. However, I am getting the following error when using the Authorization Code flow - "The authentication request has an invalid 'state' parameter". This error is coming from the /signin-oauth/code/callback/ of the developer portal. The flow works fine in the legacy Developer portal. Any thoughts?

I am having this same "The authentication request has an invalid 'state' parameter" issue when using Okta Oauth with the new portal.  It works in the legacy portal.  

I think a state parameter needs to be added:
https://github.com/Azure/api-management-developer-portal/blob/master/src/services/oauthService.ts

    public async authenticateCode(authorizationServer: AuthorizationServer): Promise<string> {
        const redirectUri = `https://${location.hostname}/signin-oauth/code/callback/${authorizationServer.name}`;

        const oauthClient = new ClientOAuth2({
            clientId: authorizationServer.clientId,
            accessTokenUri: authorizationServer.tokenEndpoint,
            authorizationUri: authorizationServer.authorizationEndpoint,
            redirectUri: redirectUri,
            scopes: authorizationServer.scopes
        });

**Comment by azaslonov** [comment] 2020-09-22 19:40
@shanemcnallie, yes you're right, we'll do that.

**Comment by nimccoll** [comment] 2020-11-09 18:10
@azaslonov has the OAuth state parameter fix been deployed?

**Comment by shanemcnallie** [comment] 2020-11-11 19:12
> @azaslonov has the OAuth state parameter fix been deployed?

I tested a few days ago and it still does not work. @azaslonov do you know when this fix is expected to be deployed?

**Comment by azaslonov** [comment] 2020-11-11 19:21
It has been deployed to some regions, I'll update this tread later when I have more info.

**Comment by jf781** [comment] 2020-12-23 19:48
Hi @azaslonov.  Hope things are going well.  I wanted to see if you had any updates on this.  I am experiencing this in the North Central US region.

**Comment by mikebudzynski** [comment] 2021-01-04 22:43
@jf781 Have you tried republishing your portal?

**Comment by shanemcnallie** [comment] 2021-01-11 15:41
> @jf781 Have you tried republishing your portal?

I have republished the portal and am still getting the message, "{"error":"invalid_request","error_description":"The authentication request has an invalid 'state' parameter."}"

**Comment by azaslonov** [comment] 2021-01-11 19:46
Hi @shanemcnallie, can you please capture the request URL (with all the parameters the console generates) to the authentication endpoint (or even better capture network logs of the whole auth session), and send it to apimportalfeedback@microsoft.com, referencing this issue?

**Comment by syedkasghar** [comment] 2021-02-03 04:20
> Hi @shanemcnallie, can you please capture the request URL (with all the parameters the console generates) to the authentication endpoint (or even better capture network logs of the whole auth session), and send it to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com), referencing this issue?

We are also facing this issue in East US2 subscription. Has this been fixed?

**Comment by shanemcnallie** [comment] 2021-02-03 14:23
> > Hi @shanemcnallie, can you please capture the request URL (with all the parameters the console generates) to the authentication endpoint (or even better capture network logs of the whole auth session), and send it to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com), referencing this issue?
> 
> We are also facing this issue in East US2 subscription. Has this been fixed?

I did send the information that @azaslonov requested and he responded with "Looks like we don’t supply state in authorization code grant flow in our backend, which seems to be mandatory for Okta. We’ll fix this in next backend release."

Does anyone know when the next backend release will be?

**Comment by mikebudzynski** [comment] 2021-02-03 19:00
> I did send the information that @azaslonov requested and he responded with "Looks like we don’t supply state in authorization code grant flow in our backend, which seems to be mandatory for Okta. We’ll fix this in next backend release."
> 
> Does anyone know when the next backend release will be?

ETA for the `state` field support is March / April.

**Comment by syedkasghar** [comment] 2021-02-08 21:36
> > I did send the information that @azaslonov requested and he responded with "Looks like we don’t supply state in authorization code grant flow in our backend, which seems to be mandatory for Okta. We’ll fix this in next backend release."
> > Does anyone know when the next backend release will be?
> 
> ETA for the `state` field support is March / April.

Thanks for the update. Will keep any eye on this issue

**Closed** 2021-07-01 18:35 UTC
Labels: (t) Improvement, (u) Test console

**Comment by alexrainman** [comment] 2021-11-09 18:38
My new developer portal is not showing the OAuth2.0 dropdown. It shows in the deprecated one though. I thought this issue was fixed.

**Comment by mikebudzynski** [comment] 2021-11-09 20:23
@alexrainman, that is not expected - please open an Azure support request to get assistance with your issue.
