### ISSUE TITLE
Copy paste functionality on Developer Portal not working

### ISSUE THREAD

**Issue by Harjindar** [Azure/api-management-developer-portal#527] opened 2020-03-05 19:23 UTC
## Reproduction steps

1. Go to Developer portal 
2. Click on 'copy'
![image](https://user-images.githubusercontent.com/37382131/76017436-e55daa80-5f1e-11ea-8317-dac01789cbee.png)

3. Click on Try It
4. Go to the text box and try to paste (Ctrl + V or with mouse)
5. Nothing is pasted

## Expected behavior

The text should have been copied to clipboard and pasted in the text box

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment] 2020-03-05 21:09
Hi @Harjindar, thanks for reporting the issue. We'll fix that.

**Comment by mikebudzynski** [comment] 2020-06-15 22:47
The issue was resolved in March.

**Comment by Harjindar** [comment] 2020-06-16 06:59
@mikebudzynski Copy paste is not working. Please check for your self and re-open the issue.

**Comment by mikebudzynski** [comment] 2020-06-18 18:59
@Harjindar we couldn't reproduce the issue on our side.

1. Are you using a managed or self-hosted portal? Did you republish it lately?
2. Which browser are you using? Which version?

**Comment by Harjindar** [comment] 2020-06-22 07:58
Hi @mikebudzynski,
I'm using managed portal and I did reublish 3 days ago. The copy paste is not working. Having said that the example is no populated (other bug) and because of this there is no longer the need to be able to copy paste. So the issue is no longer important.

Only thing is that, a user does see the copy button which is not working.

Details of the browser being used:

Google Chrome
Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by GeorgeNarcis** [comment] 2021-11-22 09:32
Any news on this ? still not working.

**Comment by mikebudzynski** [comment] 2021-11-22 20:04
@GeorgeNarcis, we now prepopulate the request body in the console. In addition to that, the "copy" button is working for me in Chrome, Edge, and Firefox.

1. Are you using a managed or self-hosted portal? Did you republish it lately?
2. Which browser are you using? Which version?
3. Do you have any browser settings that may prevent this functionality? For example, disabled JavaScript?
4. Please, try turning off all the browser extensions to make sure they aren't the cause of the problem.

**Comment by mrcarlosdev** [comment] 2024-03-29 17:16
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Closed by mrcarlosdev** 2024-03-29 17:16 UTC
Labels: (t) Bug, Response needed, P2
