### ISSUE TITLE
Node Deprecation Warning

### ISSUE THREAD

**Issue by jphines57** [Azure/api-management-developer-portal#2371] opened 2024-01-18 19:51 UTC
When using scripts.v3 and running the node ./migrate script it now shows this warning:

Exporting...
(node:14604) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by malincrist** [comment] 2024-01-25 12:55
Hello @jphines57 , thanks for reaching out. I am not able to reproduce the issue you described. With latest master, if I use the migrate script from scripts.v3, there is no deprecation warning.
![image](https://github.com/Azure/api-management-developer-portal/assets/92857141/8c149d5f-a1c5-454d-b1a3-1643bd5d2a8a)

**Comment by jphines57** [comment] 2024-01-25 16:21
Hello malincrist,
That's strange, do I need a different version of npm or node?

```
$ npm version
{
  npm: '10.3.0',
  node: '21.6.0'
}
```

**Comment by malincrist** [comment] 2024-01-26 18:01
Thanks for the clarification. Looks like `punycode` is [runtime deprecated from node version 21.0.0](https://github.com/nodejs/node/releases/tag/v21.0.0).
I was using node 20.11.0 and hence not getting the warning.

I created an internal work item to address this issue, thank you for reporting it!

**Comment by sthirthala** [comment] 2024-03-28 22:14
Looks like issue is resolved and we can close it

**Closed by sthirthala** 2024-03-28 22:14 UTC
