### ISSUE TITLE
Error add new pages "Oops, something went wrong. We are unable to complete your operation this time. Please try again."

### ISSUE THREAD

**Issue by aizefler** [Azure/api-management-developer-portal#1133] opened 2021-01-27 23:24 UTC
## Bug description

When trying to create new pages in the new Developer Portal, the error described in the title of this issue occurs.

The procedure mentioned in the documentation was followed, the RBAC was created and granted access via Powershell.

Import-Module Az 
Connect-AzAccount 
$contributorRole = Get-AzRoleDefinition "API Management Service Contributor" 
$customRole = $contributorRole 
$customRole.Id = $null
$customRole.Name = "APIM Portal Administrator" 
$customRole.Description = "This role gives the user ability to log in to the new Developer portal as administrator" 
$customRole.Actions = "Microsoft.ApiManagement/service/users/token/action" 
$customRole.IsCustom = $true 
$customRole.AssignableScopes.Clear() 
$customRole.AssignableScopes.Add('/subscriptions/XPTO') 
New-AzRoleDefinition -Role $customRole

New-AzRoleAssignment -SignInName "xpto@xpto.com" -RoleDefinitionName "APIM Portal Administrator" -Scope "/subscriptions/XPTO/resourceGroups/XPTO/providers/Microsoft.ApiManagement/service/XPTO/users/1"

![image](https://user-images.githubusercontent.com/2823190/106067050-9b545900-60dc-11eb-9227-078c32b729ed.png)

ajax.ts:157 GET https://XPTO.management.azure-api.net/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/contentTypes/block/contentItems/new-page-template?api-version=2019-12-01 404 (Not Found)

paperbits.js:2 Uncaught (in promise) TypeError: Cannot read property 'contentKey' of null
    at exports.BlockService.<anonymous> (paperbits.js:2)
    at Generator.next (<anonymous>)
    at fulfilled (paperbits.js:2)
(anonymous) @ paperbits.js:2
fulfilled @ paperbits.js:2
Promise.then (async)
step @ paperbits.js:2
(anonymous) @ paperbits.js:2
__awaiter @ paperbits.js:2
addPage @ paperbits.js:2
(anonymous) @ paperbits.js:2

## Reproduction steps

1. Open the portal in administration mode
2. In the menu add new page
3. The page is not created and the error "oops, something went wrong" appears. We are unable to complete your operation this time. Please try again."

## Expected behavior

You can create new pages on the Portal, because my goal is to create a documentation section of the API consumption processes.

## Is your portal managed or self-hosted?

Managed

## API Management service name

ahs-apim-sandboxs

## Environment

 - Operating system: Windows
 - Browser: Edge, Chrome 

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment] 2021-01-28 19:11
Hi @aizefler, this started to happen after applying RBAC rules? Or it never worked?

**Comment by aizefler** [comment] 2021-01-28 19:52
@azaslonov It never worked.

**Comment by azaslonov** [comment] 2021-01-28 20:42
Got it, let me check. I'll get back to you.

**Comment by aizefler** [comment] 2021-01-29 09:36
Thank you!

**Comment by aizefler** [comment] 2021-03-25 17:51
The problem was solved by creating a new APIM instance. We couldn't wait, sorry, thank you!

**Comment by azaslonov** [comment] 2021-03-25 19:07
Ok, I'm closing it for now, since we don't have a reproduction anymore. Sorry, for the slowness :(

**Closed by azaslonov** 2021-03-25 19:07 UTC
Labels: (t) Bug, (t) Question
