### ISSUE TITLE
Getting Invalid field 'appType' specified when trying to singup via portal 

### ISSUE THREAD

**Issue by nuwan600** [Azure/api-management-developer-portal#1954] opened 2022-09-22 04:05 UTC
## Bug description
getting Invalid field 'appType' specified
![image](https://user-images.githubusercontent.com/4129563/191654482-8a5b8507-7fa3-48f0-b7cd-ef6111f1b3e6.png)

## Reproduction steps

1. Go to Singup
2. Enter the sing up details  
3. Scroll down to click Sign up button 
4. See error top of the email text box 

## Is your portal managed or self-hosted?

Managed  

## Environment

 - Operating system: Windows 11
 - Browser: Chrome 
 - Version: 105.0.5195.54 (Official Build) (64-bit)

**Comment by innoforce-dev** [comment] 2022-09-22 09:28
We've had the same problem. See this issue herehttps://github.com/Azure/api-management-developer-portal/issues/1928#issuecomment-1238395054

Write an email to the given address. They solve it within a few hours.

**Comment by ygrik** [comment] 2022-09-28 21:50
Duplicate of [issue #1928](https://github.com/Azure/api-management-developer-portal/issues/1928)

**Closed by ygrik** 2022-09-28 21:50 UTC
