### ISSUE TITLE
Subscriptions are not displaying in the profile page if the user has a subscription with "ALL APIs" scope

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#894] opened 2020-09-07 13:33 UTC
Bug description
If the User has as a subscription with "All Apis" scope, Subscriptions(with any scope) are not displaying in the Profile page. 

## Reproduction steps

1. Add "All Apis" scope subscription for a user
2. Go to the profile page and check the subscriptions list in the developer portal

## Expected behavior
The subscription list should be displayed in the Profile page.

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows
 - Browser: Google Chrome

Note:
Subscriptions are displaying if we delete the "All Apis" scope subscription.

**Comment by mikebudzynski** [comment] 2020-09-08 18:47
We do not include "all APIs" and API-specific subscriptions by design. Can you elaborate on your scenario?

**Comment by dhandapanitrimble** [comment] 2020-09-09 06:51
Hi Mike,
  Before recent changes, If a user has an "All APIs" scope subscription then it was used to display in the subscriptions list under the profile page. After the recent changes, if the user has the "All APIs" scope subscription, none of the subscriptions are displaying in the profile page subscription list, and it's empty.
Once we delete the "All APIs" scope subscription which associated to the user, then all other subscriptions(product specific subscriptions) are displaying in the profile page.
For example. A user has below subscriptions.
1. testsub1 (product specific)
2. testsub2 (product specific)
3. testsub3 (All APIs scope)
In this case, currently, none of the above subscriptions are displaying on the profile page. Before the latest changes, it was used to display all the above(3) subscriptions.
If we delete testsub3 (All APIs scope) then other subscriptions(2) are displaying on the profile page.

**Comment by mikebudzynski** [comment] 2020-09-18 18:25
@dhandapanitrimble Thanks for bringing this up. We'll work on a fix:
- All-APIs subscriptions will never be displayed in the developer portal
- API-specific subscriptions will never be displayed in the developer portal
- Product-specific subscriptions will always be displayed in the developer portal (regardless if there's an all-APIs subscription assigned to a user)

**Comment by mkowalskigps** [comment] 2020-09-23 18:55
@mikebudzynski can you elaborate on the reason for not showing API specific subscriptions in the developer portal? We recently noticed this and had originally thought it was a bug as opposed to intentional.

**Closed** 2020-09-28 20:23 UTC
Labels: P1, bug

**Comment by mikebudzynski** [comment] 2020-09-28 22:29
@mkowalskigps We've decided to change the behavior and show all subscriptions in the user profile. Keep in mind, that users can create only Product subscriptions. API-scoped and all-APIs subscriptions can be created by service administrators.
