### ISSUE TITLE
Unable to delete Layout template in the designer

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#679] opened 2020-06-04 03:47 UTC
Hi,
I am unable to delete any Layout templates in the portal designer which contain a single forward slash for the permalink as shown below.

![image](https://user-images.githubusercontent.com/62035456/83712249-68ef7a80-a679-11ea-9da7-caffc7d14293.png)

This occurs when you delete any text after the forward slash. It renders that text control read only. I now have multiple Layouts containing a single forward slash which I am unable to delete and not sure which root layout will be used when the site is published.

**Comment by azaslonov** [comment] 2020-06-04 04:06
Hi @watson20201, yes, known issue, will be fixed in next release.

**Comment by watson20201** [comment] 2020-06-04 04:10
Do you know which layout the home page would use if several layouts have a single forward slash?
Thanks

**Comment by azaslonov** [comment] 2020-06-04 04:18
Technically, it should not allow you even save you in case of such conflict. So, we're going to check how this happens and make de-duplication in your data, then you'll be able to change the template as needed.

**Comment by watson20201** [comment] 2020-06-04 04:20
That will be great. Thanks for your help.

**Comment by michaeltnguyen** [comment] 2020-06-04 05:41
In the meanwhile, you can use the [Content Management API](https://github.com/Azure/api-management-developer-portal/wiki/Content-management-REST-API) to delete that page.

Same thing happened to me, and I had to programmatically delete it.

**Closed** 2020-08-24 22:30 UTC
Labels: P0, bug, in-progress

**Comment by npv-gmf** [comment] 2020-09-22 21:17
Hi @azaslonov @watson20201 ,
Has this issue been fixed? 
I am still not able to delete any Layout templates in the portal designer which contain a single forward slash for the permalink.

Let me know if there is an alternate way to delete these kind of layouts.

Thanks!

**Comment by pacharanero** [comment] 2020-11-20 19:04
I am experiencing the same issue. Is it still not fixed?

**Comment by azaslonov** [comment] 2020-11-20 19:38
Hi @pacharanero, the default layout cannot be removed, that is by design. Do you have some other issues with it? If yes, can you please provide repro steps?

**Comment by pacharanero** [comment] 2020-11-20 20:28
I'm trying to remove the Home layout, which is mapped to the `/` URL.

I don't want to remove the Default layout, that's the one I want to use for all pages. The URL mapping for that is `/*` so if I was able to delete the Home layout then it would take over.

There is no delete button on the Home layout menu. I've tried overriding it (I can't). I'm assuming I may have to delete it programmatically using the Content API, unless there is some other fix

**Comment by pacharanero** [comment] 2020-11-20 20:37
I can get some screenshot for you if it helps?

**Comment by pacharanero** [comment] 2020-11-22 16:39
I've explored using the Management API to edit this programmatically and in doing so understand it a bit better now.

What I am referring to as the 'Home' layout is referred to internally as the `default` layout, so I now understand what you mean @azaslonov by "You cannot delete the `default` layout".

I should probably just describe the final state I want things to be and see what is suggested as the best option. I simply want a single layout for all pages. I've customised one of the layouts extensively and would like to use this for `/` as well as `/*`. But I can't change the assignment of the 'Home' (`default`) layout from `/` - the box is greyed out.

Internally using the API I could make this layout use the same `document` as my other layout as its description. But I don't want to break stuff.

Documentation on customising the API Portal is pretty light in this area. What's the 'correct' thing to do?

**Comment by pacharanero** [comment] 2020-11-27 10:55
If it is of any help to anyone else experiencing the same issue, I have a workaround solution which did not require going to the Management API as @michaeltnguyen had to. Although interrogating the data in the API did help me understand a little more of how the application stores the layouts.

I think the bug is in the javascript UI editing app, meaning that when the route box can't be edited when it contains only `/`, even if this is in error or you want to make changes.

![image](https://user-images.githubusercontent.com/2348385/100441448-6311a980-309e-11eb-8d57-1f6d99363650.png)

The good news is that this is simply set as a 'disabled' property on the input element. In the browser console (Ctrl + Shift + I) you can see this here

`<input type="text" id="permalinkTemplate" class="form-control" placeholder="/" maxlength="2000" title="" disabled="">`

Simply unset `disabled` and you can now edit the box, and/or delete the previously un-deletable layouts. You do still need to have a layout for `/` **and** a layout for `/*` it seems. Changes do get saved. It's probably a hacky way to do it and I'm not sure what it does to the saved layouts, things went weird for a few 'publish' steps and then have been fine since.

Some official documentation around this would be good though. (And fixing the UI bug?)

**Comment by watson20201** [comment] 2020-11-30 00:44
Thanks Marcus for sharing the workaround.

**Comment by tbrad86** [comment] 2023-06-09 02:03
This is definitely not fixed. Experienced this today and the work around with inspect element posted above was the trick. Been dealing with some pretty frustrating behavior and feeling like I need to reset content and start over so we can deprecate our old dev portal.
