### ISSUE TITLE
When session is expired you can't login unless you explicit say to logout first

### ISSUE THREAD

**Issue by LockTar** [Azure/api-management-developer-portal#540] opened 2020-03-12 08:32 UTC
## Bug description

We have Azure AD integration setup. No local accounts. We have the "redirect anonymous users to login option enabled."
When a user is loggedin and leaves his tab open for a while (so his session expires) you are redirected to the login page. I can hit the login with AD button again but nothing happens. You can't leave the login page. You first need to hit the signout button and then you can login again.

## Reproduction steps

1. Go to the developer page
2. Click on sign in with azure ad (no local account)
3. Leave the page open so session expires.
4. Click login again with azure ad. You will stay now at the login page. You can't leave that page. You first need to click the signout button and login again with the azure ad button.

## Expected behavior

That you are loggedin when you click login. Not that you first need to click signout manually.

## Is your portal managed or self-hosted?

Managed

**Comment by LockTar** [comment] 2020-03-12 08:33
Maybe related to #405

**Comment by ygrik** [comment] 2020-03-12 20:55
Yes, it's related to #405 and will be fixed with the upcoming release

**Comment by azaslonov** [comment] 2020-03-12 21:38
Ok, closing as a duplicate of #405 then.

**Closed by azaslonov** 2020-03-12 21:38 UTC
Labels: to-triage
