### ISSUE TITLE
Iframes in the "Custom HTML Code" widget

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1845] opened 2022-06-29 06:40 UTC
## Bug description

I added a "Custom HTML Code" widget in order to add an iframe to my DevPortal page that shows a web page where our external wikis are hosted.

I added the following custom html code to the "Custom HTML Code" widget, saved and published the portal:
```
<html>
<head>
<style>
#outerdiv
{
   width:446px;
   height:246px;
   overflow:hidden;
   position:relative;
}
#docPage_31aa
{
   position:absolute;
   top:-412px;
   left:-318px;
   width:1280px;
   height:1200px;
}
    </style>
</head>
<body>
         <h2>Here the iframe content</h2>
<div id="docPage_31aa">
    <iframe src="https://kb.<hostname>" id="inneriframe" scrolling="yes"></iframe>
</div>
</body>
</html>
```

But in the published page, the contents of the `iframe src="https://kb.<hostname>"` are not displayed. Instead the frame remains empty.

![image](https://user-images.githubusercontent.com/58981351/176368333-f55c6647-f2f8-4298-b986-58d0c3189ff3.png)

## Expected behavior

For us it is very important to be able to embed web pages from external sources into the Developer Portal. Is there anything wrong with my custom html snippet or do you still not support  iframes in the "Custom HTML Code" widget yet? Is there any way, how I would be able to show the content area of a website through any other mechanism (workaround)?

## Is your portal managed or self-hosted?

Managed 

## Additional information

I wasn´t able to find any help for this  use case on the following Microsoft docs page:
https://docs.microsoft.com/en-us/azure/api-management/developer-portal-faq#how-do-i-add-custom-html-to-my-developer-portal

On the referenced Microsoft docs page, there is a very irritating note that I do not understand in the embedded context:
![image](https://user-images.githubusercontent.com/58981351/176369137-499eb6f6-61f5-453e-8180-badfd289255b.png)

**Comment by JMach1** [comment] 2022-07-05 16:36
Hi @AnRei123 

I was unable to reproduce the issue. I used this snippet of code, and it works just fine even after publishing.

`<html>
<head></head>
<body>
    <h2>Here the iframe content</h2>
    <iframe style="height: 1000px" src="https://bing.com/" scrolling="yes"></iframe>
</body>
</html>`

We don't support your HTML code. Just one idea that comes to my mind, your "https://kb.<hostname>" website might be set-up to block being displayed on a different domain. But it might not be the cause though. 

If you believe your code works and the issue is on our side, provide me with the name of your API Management service.

**Comment by azaslonov** [comment] 2022-07-06 01:35
@AnRei123, do you mind sending your published portal link or service name (I know you guys have lot of them) to apimportalfeedback@microsoft.com, so we could take a closer look at repro?

**Comment by azaslonov** [comment] 2022-08-02 23:49
@AnRei123, I'm closing the issue for now, since @JMach1 is following up with you offline. If you still need help, please feel free to either shoot us another email or re-open this issue, we'll be happy to assist.

**Closed by azaslonov** 2022-08-02 23:49 UTC
Labels: P1, (u) Customization
