### ISSUE TITLE
Unable to load section from library

### ISSUE THREAD

**Issue by chris9263** [Azure/api-management-developer-portal#338] opened 2019-11-25 11:49 UTC
## Bug description

I am trying to add a section in the Home layout. I have saved the top section from the default layout to the library, but when i try to insert the new section it is only loading and not finding anything in the library. When saving the section to the library i get an OK message so the section should be there.

![image](https://user-images.githubusercontent.com/37179957/69538042-b5972200-0f81-11ea-902b-68dccaa958a8.png)

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment] 2019-11-25 18:15
Hi @chris9263, thank you for reporting the issue, but this is a duplicate of #296.

**Closed by azaslonov** 2019-11-25 18:15 UTC
Labels: to-triage

**Comment by azaslonov** [comment] 2020-01-24 02:58
This issue required changes on the Management API side. It has been fixed and release should be out by Feb 21.
