### ISSUE TITLE
cURL Generation inaccurate in New Dev Portal

### ISSUE THREAD

**Issue by rcg-dev** [Azure/api-management-developer-portal#969] opened 2020-10-12 22:48 UTC
In the Developer Portal, it auto generates HTTP requests for you in different languages. However I noticed the cURL, is not very functional.

For example here is a cURL generated by Postman:

```
 curl --location --request POST 'https://example.com' \
 --header 'Content-Type: application/json' \
 --data-raw '{
     "name": "my",
     "song": "string"
 }'
```

And here is a cURL with the same url and payload generated by the dev portal.

```
 @ECHO OFF
    
 curl -v -X POST "https://example.com"
 -H "Content-Type: application/json"
 -H "Cache-Control: no-cache"
 --data-ascii "{
     ^"name^": ^"my^",
     ^"song^": ^"string^"
 }"
```

If you try to go into Postman and press Import > Raw Text and paste that second cURL it will throw a couple errors. This means people aren't able to copy and paste cURL's from the dev portal to test via Postman. Unless I'm doing something terribly wrong I think this is an issue and the syntax for the portal cURL's needs to be fixed.

**Comment by azaslonov** [comment] 2020-10-13 22:48
Fixed. The managed version will receive the fix with the next release.

**Comment by rcg-dev** [comment] 2021-03-08 21:11
I believe the issue has returned. 

Just tried generating a cURL and got this

```
@ECHO OFF

curl -v -X POST "https://api.mywebsite.net/route/"
-H "Cache-Control: no-cache"
-H "Ocp-Apim-Subscription-Key: {key}"
-H "Content-Type: application/json"
--data-ascii "{
^"asdasd^":^"asdasd^"
}"
```

**Comment by f-alizada** [comment] 2022-05-09 08:56
Hello. 
The bug is not reproducible anymore, was tested on managed versions and self-hosted (master branch).
Please see the test results below: 

**Self-hosted version curl output:** 

`curl -v -X POST "https://hostname/path" -H "Content-Type: application/json" -H "Cache-Control: no-cache" --data-raw "{ \"vehicleType\": \"train\", \"maxSpeed\": 125, \"avgSpeed\": 90, \"speedUnit\": \"mph\" }" 
`

Imported into the Postman with no errors.


**Managed version (deployed in April):**

```
curl -v -X POST "https://hostname/path"
-H "Content-Type: application/json"
-H "Cache-Control: no-cache"
--data-raw "{
    \"vehicleType\": \"train\",
    \"maxSpeed\": 125,
    \"avgSpeed\": 90,
    \"speedUnit\": \"mph\"
}"
```
Imported into the Postman with no errors. 

We could close the issue since the fixes are already merged and the bug is not reproducible.

**Closed** 2022-05-09 17:18 UTC
Labels: (t) Bug, P2
