### ISSUE TITLE
Broken icons in the administrative interface in Safari 14

### ISSUE THREAD

**Issue by ilspiert** [Azure/api-management-developer-portal#981] opened 2020-10-20 09:17 UTC
## Bug description

In Safari 14 images are not displayed right in Developer Portal publish mode.

<img width="747" alt="Safari Issue" src="https://user-images.githubusercontent.com/43613004/96565623-e6ccbf00-12c4-11eb-8814-db63c2c53acf.png">

## Reproduction steps

1. Open a Developer Portal in publish modus on a Mac with Safari 14
2. See error

## Expected behavior

See images as in other browsers.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

latest possible publish

## API Management service name

any

## Environment

 - Operating system: Mac OS Catalina 10.15.7 (19H2)
 - Browser: Safari
 - Version: 14

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by mikebudzynski** [comment] 2020-10-21 18:41
@ilspiert, we couldn't reproduce this issue.

1. Are you hitting this problem every time or was it just a one-off case?
1. If you use browser extensions, could you first disable them all and retry accessing the portal?
1. Does the interface render correctly in other browsers on your device?

**Comment by azaslonov** [comment] 2020-10-21 19:23
Hi @ilspiert, we tried versions 14 and 13.1, all looks good. I wonder if there is something else. Besides what Mike has suggested, I would look into the browser's Network traces and see if the font gets blocked there and with what error.

**Comment by ilspiert** [comment] 2020-10-22 11:14
Hi @azaslonov, @mikebudzynski,

here my feedback:

1. The issue is permanent in that constellation. Even with different internet connections.
2. No, I have no extensions installed
3. The interface is fine, only these Icons are not visible

Additional information:
- On the same system, same internet connection with an Edge (latest) everything works fine.
- I tried to make an isolated call (https://XXX.developer.azure-api.net/signin-sso?token=XXX
) in a separate tab with Network logging with the debug tools and found an interesting thing:
On safari the second "load" of the paperbits.css is with "Status: 304 Not Modified, Source: Memory Cache". On Edge that css files will be loaded again completely. That behaviour results in that on Safari the two fonts paperbits and open sans are missing - cause of the second missing reload of the css.

I will send you the network logs privately. Hope that helps to fix that.

**Comment by azaslonov** [comment] 2020-12-15 19:43
Hi @ilspiert, I don't believe we received those logs from you. Have you had a chance to send them? Or, if you did, can you please re-send?

**Comment by ilspiert** [comment] 2020-12-17 08:27
@azaslonov: I've just resend you the mail to your gmail mail address. eventually you need to check the spam folder as well. looking forward to your feedback.

**Comment by azaslonov** [comment] 2021-04-23 00:38
Looks like related to backend caching. Please use #939 for tracking. Closing this one.

**Closed by azaslonov** 2021-04-23 00:38 UTC
Labels: (t) Bug, (u) Paperbits, P1, Response needed
