### ISSUE TITLE
Not able to create a new page!

### ISSUE THREAD

**Issue by Piekop** [Azure/api-management-developer-portal#2101] opened 2023-02-15 12:23 UTC
## Bug description

Unable to create a new page (fgs)

## Reproduction steps

1. Go to the developer portal (edit mode)
2. Click on 'pages' on the paperbits menu on the left side of the screen
3. Click on add page
4. Oops something went wront

## Expected behavior

Create a new page

## Is your portal managed or self-hosted?

Managed

## API Management service name

xxx-tst-swe-apim.developer.azure-api.net

## Additional context

![image](https://user-images.githubusercontent.com/215494/219026481-91c89c3f-64d2-4912-b513-2d90f6e9c794.png)

**Comment by malincrist** [comment] 2023-02-15 14:18
Hello @Piekop, thank you for reaching out to us.
Unfortunately, I am not able to reproduce the issue you described.

I also can't find any service with the service name you provided. Could you please share the correct service name, either here either via e-mail to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com)?

**Comment by Piekop** [comment] 2023-02-15 14:31
Hello @malincrist , I've mailed you the exact service name.

Regards
Marc

**Comment by JMach1** [comment] 2023-02-23 09:56
Closing as the issue was resolved via emails.

If you are experiencing similar issue and you found this thread, please, contact Azure support.

**Closed by JMach1** 2023-02-23 09:56 UTC
