### ISSUE TITLE
API Reference page - Operation Details - response codes (4xx and 5xx) are missing

### ISSUE THREAD

**Issue by stephanieberl** [Azure/api-management-developer-portal#373] opened 2019-12-16 13:02 UTC
## Bug description

response codes (all 4xx and 5xx) are not shown in the API reference Page. 

## Reproduction steps

1. Go to api reference page
2. Click on a specific API and choose one operation
3. only the request body and the Resonse: 200 OK 
4. the used are missing

## Expected behavior

response codes 4xx and 5xx with a short description for whate they are displayed in a table like:
401 Unatuhorized
403 Authentication exception
404 Company/Cntract not found 

(these information are all included in the swagger files)

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: WIN 10
 - Browser: Google Chrome
 - Version: 77.0.3865.90

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by azaslonov** [comment] 2019-12-16 18:12
Hi @stephanieberl, I think this is a duplicate of #361. It has been fixed already, we'll start rolling it out to managed version in the next few days.

**Closed by azaslonov** 2019-12-16 18:12 UTC
Labels: to-triage
