### ISSUE TITLE
Schema keyword 'allOf' not showing msg in response frame

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#579] opened 2020-04-15 02:36 UTC
When using the "allOf" keyword in the schema specification, the portal does not display the contents.

Below is an extract of the schema using the "allOf" keyword.
![image](https://user-images.githubusercontent.com/62035456/79292186-9bf07a00-7f24-11ea-808a-9d4aa4663d5e.png)

This displays the following results in the portal.
![image](https://user-images.githubusercontent.com/62035456/79292579-95163700-7f25-11ea-8df8-450e957f90e9.png)

The whole response message is not being displayed. However if I download the specification and load it into Swagger.IO it displays fine.
Is this a bug or the use of the keyword "allOf" is not supported?

**Comment by azaslonov** [comment] 2020-04-15 03:47
Hi @watson20201, this is a duplicate of #522. The work is in progress.

**Closed by azaslonov** 2020-04-15 03:47 UTC
Labels: duplicate
