### ISSUE TITLE
MIME type error with Developer portal

### ISSUE THREAD

**Issue by dvXcode** [Azure/api-management-developer-portal#629] opened 2020-05-21 07:40 UTC
## Bug description

We are getting following MIME type errors in browser console:

Google Chrome 81.0.4044.138:

Refused to apply style from 'https://HOSTNAME*******/styles/customizations.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. theme.js:2 

Session started.
/page.html?designtime=true:1 Refused to apply style from 'https://HOSTNAME *********/styles/customizations.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
HOSTNAME *********//:1 Refused to apply style from 'https://HOSTNAME *********//styles/customizations.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
![MIME type error](https://user-images.githubusercontent.com/51912361/82535253-e6c66880-9b46-11ea-85c4-b4c64bb380be.png)

## Reproduction steps

1. Go to Azure API Management
2. Click on Portal Overview under Developer Portal
3. Click on Developer Portal button
4. See error in browser console.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser: Google Chrome 81.0.4044.138
 - Version: 81.0.4044.138

**Comment by azaslonov** [comment] 2020-05-21 21:33
Hi @dvXcode, this is just an old reference and it is not in use anymore. If you pull the latest bits it will be gone. For the managed version it will be released by the end of next week.

**Closed by azaslonov** 2020-05-21 21:33 UTC
Labels: to-triage

**Comment by lwinch2006** [comment] 2021-12-15 08:28
Hi.
As of 15th December 2021 I can say the issue still presented. MIME type mismatch and nosniff option blocks loading of styles.css
This is how developer portal looks like in Firefox (in Chrome it looks good).
![image](https://user-images.githubusercontent.com/6912915/146150829-7b5468c6-695a-494f-8ff9-284a71d86d2c.png)

**Comment by azaslonov** [comment] 2021-12-15 18:18
Hi @lwinch2006, thanks for reporting this. Could you please send your service name to apimportalfeedback@microsoft.com?

**Comment by lwinch2006** [comment] 2021-12-16 07:16
@azaslonov
Hi. Today I have checked again. It was very strange behavior in my FF. In one container tab issue was presented when clicking on dev portal link in Azure Portal. In another container tab in FF where I was logged in separately issue was away and dev portal looked like as it should. When I closed and opened FF from scratch. Issue disappeared in all container tabs in FF. So now I cannot reproduce it. Think this was something very specific to my environment, maybe saved cookies, cache in FF interfered. But from my perspective nothing needs to checked further :+1:

**Comment by azaslonov** [comment] 2021-12-16 18:29
@lwinch2006, understood. Thanks for getting back to us.

**Comment by mo-ws** [comment] 2022-10-21 14:32
We are getting this error as well. I sent the details in an email to apimportalfeedback@. 

![2022-10-21 10_29_27-MIME type ('text_html') is not a supported stylesheet - Message (HTML)](https://user-images.githubusercontent.com/84916743/197220943-d758f311-c422-4f3b-9924-2624477c3f1a.png)

**Comment by Mastard69** [comment] 2023-06-02 07:53
As of today, I have the exact same issue as previously described.
I juste took the default page, changed some styles, added a few pictures. Then I published, and it results in the same CSS error.
