### ISSUE TITLE
Anonymous view even when logged in with AAD

### ISSUE THREAD

**Issue by KevinBacas** [Azure/api-management-developer-portal#333] opened 2019-11-20 17:44 UTC
I added the ability to sign in with Azure Active Directory on the new developer portal but even when I'm logged in, I still have the anonymous view.
When I hit the sign-in button again, I'm redirected to the home page.

I configured the Identity and added the Widget on the website with the editor, published it.
It seems like I have the same problem when I use the Login/Password authentication method.

For the record, I use the default template, the only change that I made is to add the Azure Active Directory button as shown here:
![image](https://user-images.githubusercontent.com/1434393/69263467-abfa6c80-0bc5-11ea-998c-d8e02adbc802.png)

Am I missing something?

cc @dgrospelier

**Comment by azaslonov** [comment] 2019-11-20 18:22
Hi @KevinBacas, this is a duplicate of #293. I assume you're reporting the managed version of the portal. If yes, there is a fix that is still to be deployed.

**Closed by azaslonov** 2019-11-20 18:22 UTC
Labels: duplicate

**Comment by dgrospelier** [comment] 2019-11-25 13:58
> Hi @KevinBacas, this is a duplicate of #293. I assume you're reporting the managed version of the portal. If yes, there is a fix that is still to be deployed.

Hi @azaslonov, is it possible to have more details on the deployment, just to know if our version of the portal contains the fix or not? Thanks.

**Comment by azaslonov** [comment] 2019-11-25 18:09
Hi @KevinBacas, yes, the fix has been deployed last week, please give it a try.
