### ISSUE TITLE
Not able to edit text on home page and other pages in developer portal

### ISSUE THREAD

**Issue by srikanthnd** [Azure/api-management-developer-portal#2016] opened 2022-11-22 11:56 UTC
We have been using APIM Developer portal to make changes to the pages (text and images) and to customize the look and feel of the developer portal.  However, we noticed that starting today, we were not able to edit any of the contents on some of the pages.  We tried resetting the contents of the APIM developer portal to the default settings, but the behavior remained unchanged.

We can't seem to click inside of the text element as an example and change any text.  Not only text, the color, font, alignment etc of the text can't be altered even, Selecting the alignment, color etc has no effect on the text.  This happens even after resetting the portal to defaults.

![image](https://user-images.githubusercontent.com/9609176/203307756-06b12bc3-66ed-4fa3-91f7-f9477be7e65e.png)

![image](https://user-images.githubusercontent.com/9609176/203307982-6e9de910-cedf-4370-8e19-f91358e9d49d.png)

![image](https://user-images.githubusercontent.com/9609176/203334852-734ca7ab-4f88-40a9-a110-84666aa9aa97.png)

**Comment by jsorohova** [comment] 2022-11-22 14:42
Hello @srikanthnd , thank you for reporting this issue. It is a known one and we are rolling out the fix very soon. Sorry for inconveniences.

Closing as a duplicate of #2013

**Closed by jsorohova** 2022-11-22 14:42 UTC
