### ISSUE TITLE
New DevPortal: Add section from library not possible

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#451] opened 2020-01-31 09:38 UTC
## Bug description
After adding Sections to the Library they will not show up to add later. It happens with Normal Sections, bulleted Lists and Menu Items.

It seems that the following bug has not yet been resolved completely.
https://github.com/Azure/api-management-developer-portal/pull/438

## Reproduction steps
0. Reset the Portal
1. Go to 'Welcome Page'
2. Select either a section from the content or the Menu bar at the top
3. Click on 'Add to Library'
4. Click on the 'Add section' button in the content
5. Select tab card 'From Library' in the add section dialog
6. Error options: Infinite loading symbol or empty panels (see details below)

## Expected behavior
After adding a section to the library, you can select and add the saved section to any page or layout without problems.

The content of the library should be available until  manually removing it in the dialog.

## Is your portal managed or self-hosted?
Managed

## API Management service name
apiteamplayuxsource

## Environment
 - Operating system: Windows 10
 - Browser: Google Chrome, Microsoft Edge
 - Version: Chrome: 79.0.3945.130
 - Version: Microsoft Edge 44.17763.831.0

## Additional context
Screenshots from Edge: 
![AfterAddingAccessBar](https://user-images.githubusercontent.com/58420097/73527111-c85f2480-4412-11ea-9238-c30f61522729.PNG)

![StandardBlock](https://user-images.githubusercontent.com/58420097/73527073-b7161800-4412-11ea-93cd-581616318802.PNG)

Screenshots from Chrome:
![AfterAddingMenus](https://user-images.githubusercontent.com/58420097/73527005-964dc280-4412-11ea-899e-1fae927852ea.PNG)

![LibraryWorks](https://user-images.githubusercontent.com/58420097/73527217-fa708680-4412-11ea-96ec-4da3806f4406.PNG)

**Comment by ZarTrox** [comment] 2020-01-31 09:43
Additionally I found out that this Issue also is prominent in the paperbits.io demo. 

![PaperbitsIssue](https://user-images.githubusercontent.com/58420097/73529106-60aad880-4416-11ea-9230-8f47e74a276a.PNG)

**Comment by azaslonov** [comment] 2020-02-01 01:51
Hi @ZarTrox, thanks for reporting the issue, but this is a duplicate of #338. We're awaiting the backend to receive updates. After that, the issue will be gone. Current ETA - Feb 21.

**Closed by azaslonov** 2020-02-01 01:51 UTC
Labels: to-triage
