### ISSUE TITLE
Request Body properties are not displayed on the Operation Details

### ISSUE THREAD

**Issue by S-D00** [Azure/api-management-developer-portal#2426] opened 2024-02-29 10:21 UTC
## Bug description

Request body properties are not displayed within the operation details widget. 

## Reproduction steps

For this one I've deployed a new instace and I'm using the Echo API as an example however we're experiencing this accross all of our ApiM instances.

paths:
  /resource:
    get:
      summary: Retrieve resource
      description: A demonstration of an API Test
      operationId: retrieve-resource
      requestBody:
        description: The request body.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
      parameters:
        - name: param1
          in: query
          description: A sample parameter that is required and has a default value of "sample".
          required: true
          schema:
            enum:
              - sample
            type: string
            default: sample
        - name: param2
          in: query
          description: "Another sample parameter, set to not required."
          schema:
            type: number
      responses:
        "200":
          description: Returned in all cases.
          components:
  schemas:
    Test:
      type: object
      properties:
        firstName:
          type: string
          description: First Name
        lastName:
          type: string
          description: Last Name
        email:
          type: string
          description: Email Address

![image](https://github.com/Azure/api-management-developer-portal/assets/38034781/f0defbb1-6272-4f08-a123-a8d1ee699a6c)
![image](https://github.com/Azure/api-management-developer-portal/assets/38034781/74f9c59e-f38f-4041-9805-56485a694ba1)

## Expected behavior

Request body properties should be disaplyed 

![image](https://github.com/Azure/api-management-developer-portal/assets/38034781/cce910e7-e0e4-4507-b0dd-1a356ef3c8ef)

## Is your portal managed or self-hosted?

Managed

## API Management service name

[my-tes-apim-instance]

## Environment

 - Operating system: Windows
 - Browser: Chrome, Firefox
 - Version: Lastest

**Comment by malincrist** [comment] 2024-02-29 14:03
hello @S-D00 , thanks for reaching out! 
We have a regression in the current release, that creates some issues when loading APIs' definitions. We have prepared a fix and prioritized the deployment (ETA is this week/ early next week). 
If it is urgent for you, please send your apim instance(s) name(s) to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com), so we can roll them back. 
Apologies for the inconveniences and thank you for understanding!

Closing as duplicate of #2425

**Closed** 2024-03-08 10:42 UTC
